# setup.ps1 — Automated installation and setup script for the Wizard-AI environment.
# Supported Platform: Windows 10/11 (x86_64) — native PowerShell port of setup.sh
#
# Usage:  powershell -ExecutionPolicy Bypass -File setup.ps1
#
# After installation, the WIZARD_AI_DIR user environment variable is available
# and points to the directory where you cloned this repository.
#
# Requirements: git on PATH. Everything else (uv, Python venv, tools) is
# installed automatically.

param (
    [switch]$VerboseMode
)

# PowerShell 5.1 needs TLS 1.2 enabled explicitly for downloads
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

$QuietOpt = '--quiet'
if ($VerboseMode) {
    $QuietOpt = ''
    $VerbosePreference = 'Continue'
    $DebugPreference = 'Continue'
}

Write-Host '============================================================' -ForegroundColor Cyan
Write-Host '          Wizard-AI Environment Setup Wizard (Windows)' -ForegroundColor Cyan
Write-Host '============================================================' -ForegroundColor Cyan

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host '[X] git not found on PATH. Install Git for Windows first: https://git-scm.com/download/win' -ForegroundColor Red
    exit 1
}

# Resolve the absolute path of this script (= repo root)
$ScriptDir = $PSScriptRoot
$LocalBin = Join-Path $HOME '.local\bin'
$AiSkills = Join-Path $HOME '.ai-skills'

# 0. Save WIZARD_AI_DIR so skills and wrappers can reference the repo portably
Write-Host ''
Write-Host '[0/8] Registering Wizard-AI installation path...' -ForegroundColor Blue
$ConfigDir = Join-Path $HOME '.config\wizard-ai'
$null = New-Item -ItemType Directory -Force -Path $ConfigDir
$EnvFile = Join-Path $ConfigDir 'env.ps1'
$Stamp = Get-Date -Format 'yyyy-MM-dd'
@"
# Wizard-AI environment — auto-generated by setup.ps1 on $Stamp
# Do not edit manually; re-run setup.ps1 to update.
`$env:WIZARD_AI_DIR = '$ScriptDir'
if (`$env:Path -notlike "*$LocalBin*") { `$env:Path = "$LocalBin;`$(`$env:Path)" }
"@ | Set-Content -Path $EnvFile -Encoding utf8

# Persist as user environment variables (the Windows equivalent of ~/.bashrc)
[Environment]::SetEnvironmentVariable('WIZARD_AI_DIR', $ScriptDir, 'User')
$UserPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $UserPath) { $UserPath = '' }
if ($UserPath -notlike "*$LocalBin*") {
    [Environment]::SetEnvironmentVariable('Path', "$LocalBin;$UserPath", 'User')
    Write-Host "  [ok] Added $LocalBin to your user PATH" -ForegroundColor Green
}
# Export for the current session
$env:WIZARD_AI_DIR = $ScriptDir
if ($env:Path -notlike "*$LocalBin*") { $env:Path = "$LocalBin;$($env:Path)" }
Write-Host "[ok] WIZARD_AI_DIR=`"$ScriptDir`"" -ForegroundColor Green

# 1. Check/Install UV
Write-Host ''
Write-Host '[1/8] Checking for modern Python & Package Manager (uv)...' -ForegroundColor Blue
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Host 'uv not found. Installing uv via official script...' -ForegroundColor Yellow
    Invoke-RestMethod https://astral.sh/uv/install.ps1 | Invoke-Expression
    if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
        Write-Host '[X] uv installation failed. Install manually: https://docs.astral.sh/uv/' -ForegroundColor Red
        exit 1
    }
}
else {
    Write-Host "[ok] uv is already installed: $(uv --version)" -ForegroundColor Green
}

# Ensure local directories exist
$null = New-Item -ItemType Directory -Force -Path $LocalBin
$null = New-Item -ItemType Directory -Force -Path $AiSkills

# Optional: Install native Unix tools for Windows (ls, cp, grep, etc.)
Write-Host 'Checking for Microsoft.Coreutils...' -ForegroundColor Yellow
if (-not (Get-Command ls -ErrorAction SilentlyContinue | Where-Object { $_.Source -match "coreutils" })) {
    Write-Host 'Installing Microsoft.Coreutils via winget...' -ForegroundColor Yellow
    winget install Microsoft.Coreutils --accept-package-agreements --accept-source-agreements | Out-Null
}
else {
    Write-Host '[ok] Microsoft.Coreutils is already installed.' -ForegroundColor Green
}

# 2. Recreate Python Virtual Environment for wrappers
Write-Host ''
Write-Host '[2/8] Preparing Python Virtual Environment for LLMLingua & FlashRank...' -ForegroundColor Blue
$VenvDir = Join-Path $AiSkills 'venv'
if ($QuietOpt) { uv venv $VenvDir --python 3.12 --seed --quiet } else { uv venv $VenvDir --python 3.12 --seed }
$VenvPython = Join-Path $VenvDir 'Scripts\python.exe'
Write-Host 'Installing llmlingua and flashrank inside the venv (this can take a while)...' -ForegroundColor Yellow
if ($QuietOpt) { uv pip install --quiet --python $VenvPython llmlingua flashrank "aisuite[all]" } else { uv pip install --python $VenvPython llmlingua flashrank "aisuite[all]" }
Write-Host "[ok] Virtual environment ready at $VenvDir" -ForegroundColor Green

# 3. Clone and install required skill repositories if not present
Write-Host ''
Write-Host "[3/8] Setting up external git skill repositories in $AiSkills..." -ForegroundColor Blue

function Clone-IfMissing($Name, $Url) {
    $Dest = Join-Path $AiSkills $Name
    if (-not (Test-Path $Dest)) {
        Write-Host "Cloning $Name..." -ForegroundColor Yellow
        if ($QuietOpt) { git clone --quiet $Url $Dest } else { git clone $Url $Dest }
        Write-Host "  [ok] $Name cloned." -ForegroundColor Green
    }
    else {
        Write-Host "[ok] $Name already present." -ForegroundColor Green
    }
}

$Repos = @(
    @{ Name = "phantom-ui"; Url = "https://github.com/Aejkatappaja/phantom-ui.git" }
    @{ Name = "ECC"; Url = "https://github.com/affaan-m/ECC.git" }
    @{ Name = "QwenPaw"; Url = "https://github.com/agentscope-ai/QwenPaw.git" }
    @{ Name = "go-whatsapp-web-multidevice"; Url = "https://github.com/aldinokemal/go-whatsapp-web-multidevice.git" }
    @{ Name = "zvec"; Url = "https://github.com/alibaba/zvec.git" }
    @{ Name = "aisuite"; Url = "https://github.com/andrewyng/aisuite.git" }
    @{ Name = "angular"; Url = "https://github.com/angular/angular.git" }
    @{ Name = "airflow"; Url = "https://github.com/apache/airflow.git" }
    @{ Name = "kafka"; Url = "https://github.com/apache/kafka.git" }
    @{ Name = "wuzapi"; Url = "https://github.com/asternic/wuzapi.git" }
    @{ Name = "litellm"; Url = "https://github.com/BerriAI/litellm.git" }
    @{ Name = "easy-vibe"; Url = "https://github.com/datawhalechina/easy-vibe.git" }
    @{ Name = "OmniVoice-Studio"; Url = "https://github.com/debpalash/OmniVoice-Studio.git" }
    @{ Name = "deno"; Url = "https://github.com/denoland/deno.git" }
    @{ Name = "react"; Url = "https://github.com/facebook/react.git" }
    @{ Name = "react-native"; Url = "https://github.com/facebook/react-native.git" }
    @{ Name = "flutter"; Url = "https://github.com/flutter/flutter.git" }
    @{ Name = "gatsby"; Url = "https://github.com/gatsbyjs/gatsby.git" }
    @{ Name = "spec-kit"; Url = "https://github.com/github/spec-kit.git" }
    @{ Name = "hyperframes"; Url = "https://github.com/heygen-com/hyperframes.git" }
    @{ Name = "CLI-Anything"; Url = "https://github.com/HKUDS/CLI-Anything.git" }
    @{ Name = "AionUi"; Url = "https://github.com/iOfficeAI/AionUi.git" }
    @{ Name = "ionic-framework"; Url = "https://github.com/ionic-team/ionic-framework.git" }
    @{ Name = "voicebox"; Url = "https://github.com/jamiepine/voicebox.git" }
    @{ Name = "cockpit-tools"; Url = "https://github.com/jlcodes99/cockpit-tools.git" }
    @{ Name = "caveman"; Url = "https://github.com/JuliusBrussee/caveman.git" }
    @{ Name = "laravel"; Url = "https://github.com/laravel/laravel.git" }
    @{ Name = "taste-skill"; Url = "https://github.com/leonxlnx/taste-skill.git" }
    @{ Name = "mem0"; Url = "https://github.com/mem0ai/mem0.git" }
    @{ Name = "mermaid-cli"; Url = "https://github.com/mermaid-js/mermaid-cli.git" }
    @{ Name = "portfolio"; Url = "https://github.com/micio86dev/portfolio.git" }
    @{ Name = "LLMLingua"; Url = "https://github.com/microsoft/LLMLingua.git" }
    @{ Name = "markitdown"; Url = "https://github.com/microsoft/markitdown.git" }
    @{ Name = "mongo"; Url = "https://github.com/mongodb/mongo.git" }
    @{ Name = "cli-printing-press"; Url = "https://github.com/mvanhorn/cli-printing-press.git" }
    @{ Name = "mysql-server"; Url = "https://github.com/mysql/mysql-server.git" }
    @{ Name = "n8n"; Url = "https://github.com/n8n-io/n8n.git" }
    @{ Name = "serena"; Url = "https://github.com/nathanrooy/serena.git" }
    @{ Name = "nuxt"; Url = "https://github.com/nuxt/nuxt.git" }
    @{ Name = "sqz"; Url = "https://github.com/ojuschugh1/sqz.git" }
    @{ Name = "serena"; Url = "https://github.com/oraios/serena.git" }
    @{ Name = "bun"; Url = "https://github.com/oven-sh/bun.git" }
    @{ Name = "impeccable"; Url = "https://github.com/pbakaus/impeccable.git" }
    @{ Name = "claude-mem"; Url = "https://github.com/piero-io/claude-mem.git" }
    @{ Name = "pocketbase"; Url = "https://github.com/pocketbase/pocketbase.git" }
    @{ Name = "FlashRank"; Url = "https://github.com/PrithivirajDamodaran/FlashRank.git" }
    @{ Name = "cpython"; Url = "https://github.com/python/cpython.git" }
    @{ Name = "quickjs"; Url = "https://github.com/quickjs-ng/quickjs.git" }
    @{ Name = "geminiusage"; Url = "https://github.com/rmedranollamas/geminiusage.git" }
    @{ Name = "rtk"; Url = "https://github.com/rtk-ai/rtk.git" }
    @{ Name = "turbovec"; Url = "https://github.com/RyanCodrai/turbovec.git" }
    @{ Name = "graphify"; Url = "https://github.com/safishamsi/graphify.git" }
    @{ Name = "syke"; Url = "https://github.com/saxenauts/syke.git" }
    @{ Name = "antigravity-awesome-skills"; Url = "https://github.com/sickn33/antigravity-awesome-skills.git" }
    @{ Name = "supertonic"; Url = "https://github.com/supertone-inc/supertonic.git" }
    @{ Name = "kit"; Url = "https://github.com/sveltejs/kit.git" }
    @{ Name = "svelte"; Url = "https://github.com/sveltejs/svelte.git" }
    @{ Name = "personal-graph"; Url = "https://github.com/Technoculture/personal-graph.git" }
    @{ Name = "wiki-brain-skill"; Url = "https://github.com/tenfoldmarc/wiki-brain-skill.git" }
    @{ Name = "claude-mem"; Url = "https://github.com/thedotmack/claude-mem.git" }
    @{ Name = "openhuman"; Url = "https://github.com/tinyhumansai/openhuman.git" }
    @{ Name = "express-typescript-starter"; Url = "https://github.com/ToniR7/express-typescript-starter.git" }
    @{ Name = "trailbase"; Url = "https://github.com/trailbaseio/trailbase.git" }
    @{ Name = "next.js"; Url = "https://github.com/vercel/next.js.git" }
    @{ Name = "book-to-skill"; Url = "https://github.com/virgiliojr94/book-to-skill.git" }
    @{ Name = "awesome-agent-skills"; Url = "https://github.com/VoltAgent/awesome-agent-skills.git" }
    @{ Name = "awesome-design-md"; Url = "https://github.com/VoltAgent/awesome-design-md.git" }
    @{ Name = "core"; Url = "https://github.com/vuejs/core.git" }
    @{ Name = "vuetify"; Url = "https://github.com/vuetifyjs/vuetify.git" }
    @{ Name = "WordPress"; Url = "https://github.com/WordPress/WordPress.git" }
    @{ Name = "sqz"; Url = "https://github.com/yasker/sqz.git" }
    @{ Name = "lean-ctx"; Url = "https://github.com/yvgude/lean-ctx.git" }
)

foreach ($Repo in $Repos) {
    Clone-IfMissing $Repo.Name $Repo.Url
}

# Install claude-mem Python package if setup.py/pyproject.toml is present
$ClaudeMemDir = Join-Path $AiSkills 'claude-mem'
if ((Test-Path (Join-Path $ClaudeMemDir 'pyproject.toml')) -or (Test-Path (Join-Path $ClaudeMemDir 'setup.py'))) {
    if ($QuietOpt) { uv pip install --quiet --python $VenvPython -e $ClaudeMemDir } else { uv pip install --python $VenvPython -e $ClaudeMemDir }
    if ($LASTEXITCODE -ne 0) { Write-Host '  (claude-mem package install skipped)' -ForegroundColor Yellow }
}

# 4. Install UV Global Tools
Write-Host ''
Write-Host '[4/8] Installing global CLI Tools via uv tool...' -ForegroundColor Blue

function Install-UvTool($Tool, $Pkg) {
    if (-not $Pkg) { $Pkg = $Tool }
    Write-Host "Installing/Updating $Tool..." -ForegroundColor Yellow
    uv tool install --force $Pkg | Out-Null
    Write-Host "  [ok] $Tool installed." -ForegroundColor Green
}

Install-UvTool 'graphify' 'graphifyy'
Install-UvTool 'litellm'
Install-UvTool 'markitdown'
Install-UvTool 'sqz'

# Install serena (semantic code intelligence — available via uvx)
Write-Host 'Checking serena (semantic code search)...' -ForegroundColor Yellow
if (-not (Get-Command serena -ErrorAction SilentlyContinue)) {
    uv tool install --force serena-agent | Out-Null
    Write-Host '  [ok] serena installed.' -ForegroundColor Green
}
else {
    Write-Host '[ok] serena already installed.' -ForegroundColor Green
}

# 5. Fix sqz binary (pre-compiled native binary for token compression)
Write-Host ''
Write-Host '[5/8] Placing pre-compiled sqz binary...' -ForegroundColor Blue
$SqzVer = 'v1.0.5'
$Arch = $env:PROCESSOR_ARCHITECTURE

if ($Arch -eq 'AMD64') {
    $SqzUrl = "https://github.com/ojuschugh1/sqz/releases/download/$SqzVer/sqz-$SqzVer-x86_64-pc-windows-msvc.zip"
    Write-Host "Fetching compiled sqz $SqzVer binary for x86_64..." -ForegroundColor Yellow
    $TmpDir = Join-Path $env:TEMP "wizard-ai-sqz-$([System.IO.Path]::GetRandomFileName())"
    $null = New-Item -ItemType Directory -Force -Path $TmpDir
    try {
        Invoke-WebRequest -Uri $SqzUrl -OutFile (Join-Path $TmpDir 'sqz.zip') -UseBasicParsing
        Expand-Archive -Path (Join-Path $TmpDir 'sqz.zip') -DestinationPath $TmpDir -Force
        $SqzExe = Get-ChildItem -Path $TmpDir -Recurse -Filter 'sqz.exe' | Select-Object -First 1

        if ($SqzExe) {
            # Try to place in uv tool site-packages first, fallback to ~\.local\bin
            $PlacedInSitePackages = $false
            $UvToolDir = (uv tool dir).Trim()
            $SqzToolDir = Join-Path $UvToolDir 'sqz'
            if (Test-Path $SqzToolDir) {
                $SitePackages = Get-ChildItem -Path $SqzToolDir -Recurse -Directory -Filter 'site-packages' -ErrorAction SilentlyContinue | Select-Object -First 1
                if ($SitePackages) {
                    $BinDir = Join-Path $SitePackages.FullName 'sqz\_bin'
                    $null = New-Item -ItemType Directory -Force -Path $BinDir
                    Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $BinDir 'sqz.exe') -Force
                    # Also without extension, in case the package wrapper looks for "sqz"
                    Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $BinDir 'sqz') -Force
                    Write-Host '[ok] sqz binary placed in Python site-packages (x86_64).' -ForegroundColor Green
                    $PlacedInSitePackages = $true
                }
            }
            if (-not $PlacedInSitePackages) {
                Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $LocalBin 'sqz.exe') -Force
                Write-Host "[!] sqz binary placed in $LocalBin\sqz.exe (fallback)." -ForegroundColor Yellow
            }
        }
        else {
            Write-Host '[!] sqz.exe not found inside the release archive — skipping.' -ForegroundColor Yellow
        }
    }
    catch {
        Write-Host "[!] Could not download/extract sqz binary: $($_.Exception.Message)" -ForegroundColor Yellow
    }
    finally {
        Remove-Item -Path $TmpDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}
else {
    Write-Host "[X] No pre-compiled sqz Windows binary for architecture '$Arch'. Compile sqz manually." -ForegroundColor Red
}

# 6. Copy and configure CLI Wrappers
Write-Host ''
Write-Host "[6/8] Deploying custom AI CLI wrappers to $LocalBin..." -ForegroundColor Blue
$WrappersSrc = Join-Path $ScriptDir 'bin\windows'
Copy-Item -Path (Join-Path $WrappersSrc '*.ps1') -Destination $LocalBin -Force
$null = New-Item -ItemType Directory -Force -Path (Join-Path $LocalBin 'lib')
Copy-Item -Path (Join-Path $WrappersSrc 'lib\*') -Destination (Join-Path $LocalBin 'lib') -Recurse -Force

# Generate .cmd shims so wrappers can be invoked as plain commands
# (e.g. "ai-help") from cmd.exe, PowerShell, and other AI agents.
function New-CmdShim($CommandName, $Ps1Name) {
    $ShimPath = Join-Path $LocalBin "$CommandName.cmd"
    $Content = "@echo off`r`npowershell -NoProfile -ExecutionPolicy Bypass -File `"%~dp0$Ps1Name`" %*"
    Set-Content -Path $ShimPath -Value $Content -Encoding Ascii
}

$Wrappers = Get-ChildItem -Path $WrappersSrc -Filter '*.ps1'
foreach ($W in $Wrappers) {
    New-CmdShim $W.BaseName $W.Name
}
# gemini-usage is an alias of ai-usage (same script, no duplicate files)
New-CmdShim 'gemini-usage' 'ai-usage.ps1'
Write-Host "[ok] $($Wrappers.Count) wrapper scripts installed to $LocalBin (with gemini-usage shim)" -ForegroundColor Green

# 7. Install Skills for all agents
Write-Host ''
Write-Host '[7/8] Installing AI agent skills...' -ForegroundColor Blue
$SkillsDst = Join-Path $HOME '.gemini\config\skills'
$null = New-Item -ItemType Directory -Force -Path $SkillsDst
Copy-Item -Path (Join-Path $ScriptDir 'skills\*') -Destination $SkillsDst -Recurse -Force
$SkillCount = (Get-ChildItem -Path (Join-Path $ScriptDir 'skills') -Directory | Measure-Object).Count
Write-Host "[ok] $SkillCount skills installed to $SkillsDst" -ForegroundColor Green

Write-Host 'Syncing skills to Claude Code, Amp, and other agents...' -ForegroundColor Yellow
& (Join-Path $LocalBin 'ai-sync-skills.ps1')

# 8. Auto-Update Configuration
Write-Host ''
Write-Host '[8/8] Auto-Update Configuration...' -ForegroundColor Blue
Write-Host 'Do you want to enable automatic background updates at system logon? [Y/n] (Auto-yes in 10s) ' -ForegroundColor Yellow -NoNewline

$EnableUpdate = 'Y'
$TimeoutSeconds = 10
$Watch = [System.Diagnostics.Stopwatch]::StartNew()
$Host.UI.RawUI.FlushInputBuffer()
while ($Watch.Elapsed.TotalSeconds -lt $TimeoutSeconds) {
    if ($Host.UI.RawUI.KeyAvailable) {
        $KeyInfo = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        if ($KeyInfo.Character -ne 0) {
            $Key = $KeyInfo.Character
            Write-Host $Key
            if ($Key -eq 'n' -or $Key -eq 'N') { $EnableUpdate = 'N' }
            break
        }
    }
    Start-Sleep -Milliseconds 100
}
if (-not $Host.UI.RawUI.KeyAvailable) { Write-Host '' }

$StartupFolder = [Environment]::GetFolderPath('Startup')
$StartupShortcut = Join-Path $StartupFolder "WizardAI-AutoUpdate.lnk"

if ($EnableUpdate -eq 'Y') {
    Write-Host "  [ok] Enabling automatic background updates at logon..." -ForegroundColor Green
    try {
        $WshShell = New-Object -ComObject WScript.Shell
        $Shortcut = $WshShell.CreateShortcut($StartupShortcut)
        $Shortcut.TargetPath = "powershell.exe"
        $Shortcut.Arguments = "-WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -File `"$LocalBin\ai-update.ps1`" -Quiet"
        $Shortcut.Save()
        Write-Host "  [ok] Startup shortcut installed for user." -ForegroundColor Green
    }
    catch {
        Write-Host "  [!] Could not create startup shortcut: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}
else {
    Write-Host "  Auto-updates disabled. Update manually using 'ai-update'." -ForegroundColor Yellow
    if (Test-Path $StartupShortcut) {
        Remove-Item $StartupShortcut -Force
    }
}

# 9. Final summary
Write-Host ''
Write-Host '============================================================' -ForegroundColor Green
Write-Host '      Wizard-AI Environment Installed Successfully!' -ForegroundColor Green
Write-Host '============================================================' -ForegroundColor Green
Write-Host ''
Write-Host 'Available commands in your terminal:'
Write-Host '  ai-help      ' -ForegroundColor Cyan -NoNewline; Write-Host '- Central hub for all AI commands'
Write-Host '  ai-usage     ' -ForegroundColor Cyan -NoNewline; Write-Host '- View Gemini usage statistics and token budget'
Write-Host '  ai-graph     ' -ForegroundColor Cyan -NoNewline; Write-Host '- Run Graphify to map codebases to knowledge graphs'
Write-Host '  ai-compress  ' -ForegroundColor Cyan -NoNewline; Write-Host '- Compress prompt context via LLMLingua (up to 20x)'
Write-Host '  ai-rerank    ' -ForegroundColor Cyan -NoNewline; Write-Host '- Re-rank list components for RAG via FlashRank'
Write-Host '  ai-squeeze   ' -ForegroundColor Cyan -NoNewline; Write-Host '- Compress CLI outputs / files via Sqz'
Write-Host '  ai-convert   ' -ForegroundColor Cyan -NoNewline; Write-Host '- Extract clean Markdown from PDF, DOCX, images, etc.'
Write-Host '  ai-mem       ' -ForegroundColor Cyan -NoNewline; Write-Host '- Access persistent semantic memory (claude-mem)'
Write-Host '  ai-sync-skills ' -ForegroundColor Cyan -NoNewline; Write-Host '- Sync skills across all AI agents'
Write-Host ''
Write-Host 'Important: open a NEW terminal to load the updated PATH.' -ForegroundColor Yellow
Write-Host ''
Write-Host 'Your Wizard-AI directory: ' -ForegroundColor Yellow -NoNewline; Write-Host $ScriptDir -ForegroundColor Magenta
Write-Host 'Skills: ' -ForegroundColor Yellow -NoNewline; Write-Host $SkillsDst -ForegroundColor Magenta
Write-Host 'CLIs:   ' -ForegroundColor Yellow -NoNewline; Write-Host $LocalBin -ForegroundColor Magenta
Write-Host ''
Write-Host "Run 'ai-help' to see all available tools and their usage." -ForegroundColor Cyan
