# setup.ps1 — Automated installation and setup script for the Wizard-AI environment.
# Supported Platform: Windows 10/11 (x86_64) — native PowerShell port of setup.sh
#
# Usage:  powershell -ExecutionPolicy Bypass -File setup.ps1
#
# After installation, the WIZARD_AI_DIR user environment variable is available
# and points to the directory where you cloned this repository.
#
# Requirements: git on PATH. Everything else (uv, Python venv, tools) is
# installed automatically.

param (
    [switch]$VerboseMode
)

# -------------------------------------------------------------
# Detailed Logging System (Human & LLM / JSON)
# -------------------------------------------------------------
$GlobalLogFile = Join-Path $HOME '.wizard-ai\setup.log'
$GlobalJsonLog = Join-Path $HOME '.wizard-ai\setup.json'

function Write-Log {
    param(
        [Parameter(Mandatory=$true, ValueFromPipeline=$true, Position=0)]
        [string]$Message,
        [ConsoleColor]$ForegroundColor = 'Gray',
        [switch]$NoNewline
    )
    
    $Timestamp = (Get-Date).ToString('o')
    $CleanMessage = $Message -replace '\e\[[0-9;]*m', '' # Remove ANSI
    
    # JSON Log
    $LogEntry = @{
        timestamp = $Timestamp
        level     = 'INFO'
        message   = $CleanMessage
    }
    $JsonString = $LogEntry | ConvertTo-Json -Compress
    Add-Content -Path $GlobalJsonLog -Value $JsonString
    
    # Text Log
    Add-Content -Path $GlobalLogFile -Value "[$Timestamp] $CleanMessage"
    
    # Console Output
    if ($NoNewline) {
        Write-Host $Message -ForegroundColor $ForegroundColor -NoNewline
    } else {
        Write-Host $Message -ForegroundColor $ForegroundColor
    }
}
# -------------------------------------------------------------


# PowerShell security hardening: Enforce TLS 1.2 and TLS 1.3 explicitly
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13

$QuietOpt = '--quiet'
if ($VerboseMode) {
    $QuietOpt = ''
    $VerbosePreference = 'Continue'
    $DebugPreference = 'Continue'
}

Write-Log '============================================================' -ForegroundColor Cyan
Write-Log '          Wizard-AI Environment Setup Wizard (Windows)' -ForegroundColor Cyan
Write-Log '============================================================' -ForegroundColor Cyan

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Log '[X] git not found on PATH. Install Git for Windows first: https://git-scm.com/download/win' -ForegroundColor Red
    exit 1
}

# Resolve the absolute path of this script (= repo root)
$ScriptDir = $PSScriptRoot
$LocalBin = Join-Path $HOME '.local\bin'
$AiSkills = Join-Path $HOME '.wizard-ai'

# 0. Save WIZARD_AI_DIR so skills and wrappers can reference the repo portably
Write-Log ' '
Write-Log '[0/8] Registering Wizard-AI installation path...' -ForegroundColor Blue
$ConfigDir = Join-Path $HOME '.config\wizard-ai'
$null = New-Item -ItemType Directory -Force -Path $ConfigDir
$EnvFile = Join-Path $ConfigDir 'env.ps1'
$Stamp = Get-Date -Format 'yyyy-MM-dd'
@"
# Wizard-AI environment — auto-generated by setup.ps1 on $Stamp
# Do not edit manually; re-run setup.ps1 to update.
`$env:WIZARD_AI_DIR = '$ScriptDir'
if (`$env:Path -notlike "*$LocalBin*") { `$env:Path = "$LocalBin;`$(`$env:Path)" }
"@ | Set-Content -Path $EnvFile -Encoding utf8

# Persist as user environment variables (the Windows equivalent of ~/.bashrc)
[Environment]::SetEnvironmentVariable('WIZARD_AI_DIR', $ScriptDir, 'User')
$UserPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $UserPath) { $UserPath = '' }
if ($UserPath -notlike "*$LocalBin*") {
    [Environment]::SetEnvironmentVariable('Path', "$LocalBin;$UserPath", 'User')
    Write-Log "  [ok] Added $LocalBin to your user PATH" -ForegroundColor Green
}
# Export for the current session
$env:WIZARD_AI_DIR = $ScriptDir
if ($env:Path -notlike "*$LocalBin*") { $env:Path = "$LocalBin;$($env:Path)" }
Write-Log "[ok] WIZARD_AI_DIR=`"$ScriptDir`"" -ForegroundColor Green

# 1. Check/Install UV
Write-Log ' '
Write-Log '[1/8] Checking for modern Python & Package Manager (uv)...' -ForegroundColor Blue
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Log 'uv not found. Installing uv via official script...' -ForegroundColor Yellow
    # SECURITY: Executing scripts directly from the internet via pipe is a security risk.
    # Ideally, download the script, verify its hash/signature, and then execute it.
    Invoke-RestMethod https://astral.sh/uv/install.ps1 | Invoke-Expression
    if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
        Write-Log '[X] uv installation failed. Install manually: https://docs.astral.sh/uv/' -ForegroundColor Red
        exit 1
    }
}
else {
    Write-Log "[ok] uv is already installed: $(uv --version)" -ForegroundColor Green
}

# Ensure local directories exist
$null = New-Item -ItemType Directory -Force -Path $LocalBin
$null = New-Item -ItemType Directory -Force -Path $AiSkills

# Optional: Install native Unix tools for Windows (ls, cp, grep, etc.)
Write-Log 'Checking for Microsoft.Coreutils...' -ForegroundColor Yellow
if (-not (Get-Command ls -ErrorAction SilentlyContinue | Where-Object { $_.Source -match "coreutils" })) {
    Write-Log '  > Command: winget install Microsoft.Coreutils --accept-package-agreements --accept-source-agreements --verbose-logs' -ForegroundColor DarkGray
    Write-Log '  > Note: If this hangs, check for hidden UAC prompts in your taskbar, or press Enter.' -ForegroundColor DarkGray
    winget install Microsoft.Coreutils --accept-package-agreements --accept-source-agreements --verbose-logs
    Write-Log '  > winget command finished.' -ForegroundColor DarkGray
}
else {
    Write-Log '[ok] Microsoft.Coreutils is already installed.' -ForegroundColor Green
}

# Ensure MSVC C++ Build Tools are installed for headroom-ai compilation
Write-Log 'Checking for MSVC C++ Build Tools...' -ForegroundColor Yellow
$VsWherePath = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
$HasMsvc = $false
if (Test-Path $VsWherePath) {
    $MsvcCheck = & $VsWherePath -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if ($MsvcCheck) { $HasMsvc = $true }
}
if (-not $HasMsvc) {
    Write-Log 'MSVC C++ Build Tools not found. Installing via winget (this may take a few minutes)...' -ForegroundColor Yellow
    Write-Log '  > Note: A UAC prompt may appear in the background for Visual Studio Installer. Please accept it.' -ForegroundColor Yellow
    $VsOverride = '--quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended'
    Write-Log "  > Command: winget install --id Microsoft.VisualStudio.2022.BuildTools --exact --force --accept-package-agreements --accept-source-agreements --override `"$VsOverride`" --verbose-logs" -ForegroundColor DarkGray
    winget install --id Microsoft.VisualStudio.2022.BuildTools --exact --force --accept-package-agreements --accept-source-agreements --override $VsOverride --verbose-logs
    Write-Log '  > winget command finished.' -ForegroundColor DarkGray
    Write-Log '[ok] MSVC C++ Build Tools installed.' -ForegroundColor Green
} else {
    Write-Log '[ok] MSVC C++ Build Tools are already installed.' -ForegroundColor Green
}

# 2. Recreate Python Virtual Environment for wrappers
Write-Log ' '
Write-Log '[2/8] Preparing Python Virtual Environment for LLMLingua & FlashRank...' -ForegroundColor Blue
$VenvDir = Join-Path $AiSkills 'venv'
if ($QuietOpt) { uv venv $VenvDir --python 3.12 --seed --quiet } else { uv venv $VenvDir --python 3.12 --seed }
$VenvPython = Join-Path $VenvDir 'Scripts\python.exe'
Write-Log 'Installing llmlingua and flashrank inside the venv (this can take a while)...' -ForegroundColor Yellow
if ($QuietOpt) { uv pip install --quiet --python $VenvPython llmlingua flashrank "aisuite[all]" } else { uv pip install --python $VenvPython llmlingua flashrank "aisuite[all]" }
Write-Log "[ok] Virtual environment ready at $VenvDir" -ForegroundColor Green

# 3. Clone and install required skill repositories if not present
Write-Log ' '
Write-Log "[3/8] Setting up external git skill repositories in $AiSkills..." -ForegroundColor Blue

function Clone-SkillRepo($Url, $DestName) {
    $DestDir = Join-Path $AiSkills $DestName
    if (-not (Test-Path $DestDir)) {
        Write-Log "Cloning $DestName from GitHub..." -ForegroundColor Yellow
        if ($QuietOpt) {
            git clone --depth 1 --quiet $Url $DestDir
        } else {
            git clone --depth 1 $Url $DestDir
        }
        if ($LASTEXITCODE -ne 0) {
            Write-Log "  [!] $DestName clone failed" -ForegroundColor Red
        } else {
            Write-Log "  [ok] $DestName cloned." -ForegroundColor Green
        }
    } else {
        Write-Log "  [ok] $DestName is already present." -ForegroundColor Green
    }
}

Clone-SkillRepo 'https://github.com/thedotmack/claude-mem.git' 'claude-mem'
Clone-SkillRepo 'https://github.com/chopratejas/headroom.git' 'headroom'
Clone-SkillRepo 'https://github.com/antvis/Infographic.git' 'Infographic'
Clone-SkillRepo 'https://github.com/mukul975/Anthropic-Cybersecurity-Skills.git' 'cybersecurity-skills'

Write-Log "Cloning/Verifying ECC and caveman repositories inside ~/.wizard-ai/..." -ForegroundColor Cyan
Clone-SkillRepo 'https://github.com/vekexasia/wslens.git' 'wslens'
if (Test-Path (Join-Path $AiSkills 'wslens\install.ps1')) {
    Write-Log "Installing wslens backend..." -ForegroundColor Yellow
    # Save original directory
    $OldDir = Get-Location
    Set-Location (Join-Path $AiSkills 'wslens')
    & .\install.ps1
    Set-Location $OldDir
    
    # Also create a wrapper for wz-ai so we can do 'wz-ai wslens'
    $WslensWrapper = Join-Path $LocalBin 'wz-ai-wslens.ps1'
    "<#
.SYNOPSIS
Wrapper for wslens
#>
if (`$args.Count -eq 0) { wslens } else { wslens @args }" | Set-Content -Path $WslensWrapper -Encoding utf8
}
Clone-SkillRepo 'https://github.com/affaan-m/ECC.git' 'ECC'
Clone-SkillRepo 'https://github.com/JuliusBrussee/caveman.git' 'caveman'

if (Get-Command npm -ErrorAction SilentlyContinue) {
    Write-Log "Attempting optional NPM global installations (ECC)..." -ForegroundColor Yellow
    try { npm install -g ecc-universal 2>$null } catch { Write-Log "Note: ecc-universal npm install skipped." -ForegroundColor DarkGray }
} else {
    Write-Log "NPM not found. Using cloned git repos for ECC." -ForegroundColor Yellow
}

Write-Log "Installing Caveman agent skill globally..." -ForegroundColor Yellow
try {
    $tempPs1 = Join-Path $env:TEMP "caveman_install.ps1"
    Invoke-RestMethod https://raw.githubusercontent.com/JuliusBrussee/caveman/main/install.ps1 -OutFile $tempPs1
    $proc = Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$tempPs1`"" -Wait -NoNewWindow -PassThru
    Remove-Item $tempPs1 -ErrorAction SilentlyContinue
    if ($proc.ExitCode -eq 0) {
        Write-Log "  [ok] Caveman skill installed successfully." -ForegroundColor Green
    } else {
        Write-Log "  [!] Caveman skill installation returned exit code $($proc.ExitCode)." -ForegroundColor Yellow
    }
} catch {
    Write-Log "  [!] Failed to install caveman. You can install manually: irm https://raw.githubusercontent.com/JuliusBrussee/caveman/main/install.ps1 | iex" -ForegroundColor Red
}
Clone-SkillRepo 'https://github.com/yvgude/lean-ctx.git' 'lean-ctx'

# 4. Install UV Global Tools
Write-Log ' '
Write-Log '[4/8] Installing global CLI Tools via uv tool...' -ForegroundColor Blue

function Install-UvTool($Tool, $Pkg) {
    if (-not $Pkg) { $Pkg = $Tool }
    Write-Log "Installing/Updating $Tool..." -ForegroundColor Yellow
    
    # Run uv tool install and capture stderr
    $err = $(uv tool install --force $Pkg 2>&1)
    if ($LASTEXITCODE -eq 0) {
        Write-Log "  [ok] $Tool installed." -ForegroundColor Green
    } else {
        if ($Tool -eq 'headroom') {
            Write-Log "  [!] Failed to install $Tool (MSVC C++ Build Tools required). Skipping headroom setup, proceeding with the rest..." -ForegroundColor Yellow
        } else {
            Write-Log "  [!] Failed to install $Tool (exit code $LASTEXITCODE). You may need to install MSVC C++ Build Tools." -ForegroundColor Red
            Write-Log "      Details: $err" -ForegroundColor DarkGray
        }
    }
}

Install-UvTool 'graphify' 'graphifyy[all]'
Install-UvTool 'litellm' 'litellm[proxy]'
Install-UvTool 'markitdown'
Install-UvTool 'sqz'
Install-UvTool 'headroom' 'headroom-ai'

# Install serena (semantic code intelligence — available via uvx)
Write-Log 'Checking serena (semantic code search)...' -ForegroundColor Yellow
if (-not (Get-Command serena -ErrorAction SilentlyContinue)) {
    uv tool install --force serena-agent | Out-Null
    Write-Log '  [ok] serena installed.' -ForegroundColor Green
}
else {
    Write-Log '[ok] serena already installed.' -ForegroundColor Green
}

# 5. Fix sqz binary (pre-compiled native binary for token compression)
Write-Log ' '
Write-Log '[5/8] Placing pre-compiled sqz binary...' -ForegroundColor Blue
$SqzVer = ((Invoke-RestMethod -Uri 'https://api.github.com/repos/ojuschugh1/sqz/releases/latest' -UseBasicParsing -ErrorAction SilentlyContinue).tag_name)
if (-not $SqzVer) { $SqzVer = 'v1.3.0' }
$Arch = $env:PROCESSOR_ARCHITECTURE

if ($Arch -eq 'AMD64') {
    $SqzUrl = "https://github.com/ojuschugh1/sqz/releases/download/$SqzVer/sqz-$SqzVer-x86_64-pc-windows-msvc.zip"
    Write-Log "Fetching compiled sqz $SqzVer binary for x86_64..." -ForegroundColor Yellow
    $TmpDir = Join-Path $env:TEMP ([guid]::NewGuid().ToString())
    $null = New-Item -ItemType Directory -Force -Path $TmpDir
    try {
        # Security Hardening: UseBasicParsing prevents IE DOM parsing vulnerabilities
        Invoke-WebRequest -Uri $SqzUrl -OutFile "$TmpDir\sqz.zip" -UseBasicParsing
        Expand-Archive -Path (Join-Path $TmpDir 'sqz.zip') -DestinationPath $TmpDir -Force
        $SqzExe = Get-ChildItem -Path $TmpDir -Recurse -Filter 'sqz.exe' | Select-Object -First 1

        if ($SqzExe) {
            # Verify executable runs before overwriting working installation
            $IsWorking = $false
            try {
                & $SqzExe.FullName --help 2>&1 | Out-Null
                $IsWorking = $true
            } catch { $IsWorking = $false }

            if (-not $IsWorking) {
                Write-Log "[!] Downloaded sqz $SqzVer binary failed execution check. Keeping previous working installation." -ForegroundColor Yellow
            } else {
                # Try to place in uv tool site-packages first, fallback to ~\.local\bin
                $PlacedInSitePackages = $false
                $UvToolDir = (uv tool dir 2>$null).Trim()
                if ($UvToolDir -and (Test-Path $UvToolDir)) {
                    $SqzToolDir = Join-Path $UvToolDir 'sqz'
                    if (Test-Path $SqzToolDir) {
                        $SitePackages = Get-ChildItem -Path $SqzToolDir -Recurse -Directory -Filter 'site-packages' -ErrorAction SilentlyContinue | Select-Object -First 1
                        if ($SitePackages) {
                            $BinDir = Join-Path $SitePackages.FullName 'sqz\_bin'
                            $null = New-Item -ItemType Directory -Force -Path $BinDir
                            Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $BinDir 'sqz.exe') -Force
                            Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $BinDir 'sqz') -Force
                            Write-Log "[ok] sqz $SqzVer binary placed safely in Python site-packages (x86_64)." -ForegroundColor Green
                            $PlacedInSitePackages = $true
                        }
                    }
                }
                if (-not $PlacedInSitePackages) {
                    Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $LocalBin 'sqz.exe') -Force
                    Write-Log "[!] sqz $SqzVer binary placed safely in $LocalBin\sqz.exe (fallback)." -ForegroundColor Yellow
                }
            }
        }
        else {
            Write-Log '[!] sqz.exe not found inside the release archive — keeping previous working version.' -ForegroundColor Yellow
        }
    }
    catch {
        Write-Log "[!] Could not download/extract sqz $SqzVer binary: $($_.Exception.Message). Keeping previous working version." -ForegroundColor Yellow
    }
    finally {
        Remove-Item -Path $TmpDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}
else {
    Write-Log "[X] No pre-compiled sqz Windows binary for architecture '$Arch'. Compile sqz manually." -ForegroundColor Red
}

# 6. Copy and configure CLI Wrappers
Write-Log ' '
Write-Log "[6/8] Deploying custom AI CLI wrappers to $LocalBin..." -ForegroundColor Blue
$WrappersSrc = Join-Path $ScriptDir 'bin\windows'

# Security: Ensure paths are strictly within the project directory to prevent path traversal
$ResolvedSrc = Resolve-Path $WrappersSrc -ErrorAction SilentlyContinue
if (-not $ResolvedSrc -or -not $ResolvedSrc.Path.StartsWith($ScriptDir)) {
    Write-Log "[X] Invalid wrappers source path. Potential path traversal detected." -ForegroundColor Red
    exit 1
}

Copy-Item -Path (Join-Path $WrappersSrc '*.ps1') -Destination $LocalBin -Force
$null = New-Item -ItemType Directory -Force -Path (Join-Path $LocalBin 'lib')
Copy-Item -Path (Join-Path $WrappersSrc 'lib\*') -Destination (Join-Path $LocalBin 'lib') -Recurse -Force

# Generate .cmd shims so wrappers can be invoked as plain commands
# (e.g. "wz-ai") from cmd.exe, PowerShell, and other AI agents.
function New-CmdShim($CommandName, $Ps1Name) {
    $ShimPath = Join-Path $LocalBin "$CommandName.cmd"
    $Content = "@echo off`r`npowershell -NoProfile -ExecutionPolicy Bypass -File `"%~dp0$Ps1Name`" %*"
    Set-Content -Path $ShimPath -Value $Content -Encoding Ascii
}

# Only create the main dispatcher shim to prevent PATH pollution
New-CmdShim 'wz-ai' 'wz-ai.ps1'

Write-Log "[ok] Main dispatcher wz-ai.cmd installed to $LocalBin (subcommands are encapsulated)" -ForegroundColor Green

# 7. Install Skills for all agents (hierarchical → flat)
Write-Log ' '
Write-Log '[7/8] Installing AI agent skills...' -ForegroundColor Blue
$SkillsDst = Join-Path $HOME '.gemini\config\skills'
$null = New-Item -ItemType Directory -Force -Path $SkillsDst
$SkillCount = 0
# Find every SKILL.md inside categorized directories and copy its parent folder flatly
Get-ChildItem -Path (Join-Path $ScriptDir 'skills') -Filter 'SKILL.md' -Recurse -File | ForEach-Object {
    $SkillDir = $_.DirectoryName
    $SkillName = Split-Path $SkillDir -Leaf
    $DestDir = Join-Path $SkillsDst $SkillName
    $null = New-Item -ItemType Directory -Force -Path $DestDir
    Copy-Item -Path (Join-Path $SkillDir '*') -Destination $DestDir -Recurse -Force -ErrorAction SilentlyContinue
    $SkillCount++
}
# Also copy skills.json for reference
Copy-Item -Path (Join-Path $ScriptDir 'skills\skills.json') -Destination $SkillsDst -Force -ErrorAction SilentlyContinue
Write-Log "[ok] $SkillCount skills installed to $SkillsDst" -ForegroundColor Green

Write-Log 'Syncing skills to Claude Code, Amp, and other agents...' -ForegroundColor Yellow
& (Join-Path $LocalBin 'wz-ai-sync-skills.ps1')

# 8. Auto-Update Configuration
Write-Log ' '
Write-Log '[8/8] Auto-Update Configuration...' -ForegroundColor Blue
Write-Log 'Do you want to enable automatic background updates at system logon? [Y/n] (Auto-yes in 10s) ' -ForegroundColor Yellow -NoNewline

$EnableUpdate = 'Y'
$TimeoutSeconds = 10
$Watch = [System.Diagnostics.Stopwatch]::StartNew()
try {
    $Host.UI.RawUI.FlushInputBuffer()
    while ($Watch.Elapsed.TotalSeconds -lt $TimeoutSeconds) {
        if ($Host.UI.RawUI.KeyAvailable) {
            $KeyInfo = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
            if ($KeyInfo.Character -ne 0) {
                $Key = $KeyInfo.Character
                Write-Log $Key
                if ($Key -eq 'n' -or $Key -eq 'N') { $EnableUpdate = 'N' }
                break
            }
        }
        Start-Sleep -Milliseconds 100
    }
} catch {
    Write-Log "[!] Interactive prompt not supported in this terminal. Defaulting to Y in $TimeoutSeconds seconds..." -ForegroundColor Yellow
    Start-Sleep -Seconds $TimeoutSeconds
}
if (-not $Host.UI.RawUI.KeyAvailable) { Write-Log ' ' }

$StartupFolder = [Environment]::GetFolderPath('Startup')
$StartupShortcut = Join-Path $StartupFolder "WizardAI-AutoUpdate.lnk"

if ($EnableUpdate -eq 'Y') {
    Write-Log "  [ok] Enabling automatic background updates at logon..." -ForegroundColor Green
    $UpdateScriptPath = Join-Path $LocalBin 'wz-ai-update.ps1'
    
    # Security: Ensure the file exists before creating the shortcut
    if (Test-Path $UpdateScriptPath) {
        try {
            $WshShell = New-Object -ComObject WScript.Shell
            $Shortcut = $WshShell.CreateShortcut($StartupShortcut)
            $Shortcut.TargetPath = "powershell.exe"
            $Shortcut.Arguments = "-WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -File `"$UpdateScriptPath`" -Quiet"
            $Shortcut.Save()
            Write-Log "  [ok] Startup shortcut installed for user." -ForegroundColor Green
        }
        catch {
            Write-Log "  [!] Could not create startup shortcut: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    } else {
        Write-Log "  [!] Update script not found at $UpdateScriptPath. Skipping auto-update setup." -ForegroundColor Red
    }
}
else {
    Write-Log "  Auto-updates disabled. Update manually using 'wz-ai update'." -ForegroundColor Yellow
    if (Test-Path $StartupShortcut) {
        Remove-Item $StartupShortcut -Force
    }
}

# 9. Final summary
Write-Log ' '
Write-Log '============================================================' -ForegroundColor Green
Write-Log '      Wizard-AI Environment Installed Successfully!' -ForegroundColor Green
Write-Log '============================================================' -ForegroundColor Green
Write-Log ' '
Write-Log ' '
Write-Log 'To see all available tools, wrappers, and their usage, simply run:'
Write-Log '  wz-ai help' -ForegroundColor Cyan
Write-Log ' '
Write-Log 'Important: open a NEW terminal to load the updated PATH.' -ForegroundColor Yellow
Write-Log ' '
Write-Log 'Your Wizard-AI directory: ' -ForegroundColor Yellow -NoNewline; Write-Log $ScriptDir -ForegroundColor Magenta
Write-Log 'Skills: ' -ForegroundColor Yellow -NoNewline; Write-Log $SkillsDst -ForegroundColor Magenta
Write-Log 'CLIs:   ' -ForegroundColor Yellow -NoNewline; Write-Log $LocalBin -ForegroundColor Magenta
Write-Log ' '
Write-Log "Run 'wz-ai help' to see all available tools and their usage." -ForegroundColor Cyan
