#!/usr/bin/env bash
# setup.sh — Automated installation and setup script for the Wizard-AI environment.
# Supported Platform: Linux (x86_64 / aarch64) | macOS (x86_64 / arm64)
#
# After installation, the variable $WIZARD_AI_DIR is available in your shell
# and points to the directory where you cloned this repository.

set -euo pipefail

# ANSI color codes for premium terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}============================================================"
echo -e "         🧙‍♂️  Wizard-AI Environment Setup Wizard"
echo -e "============================================================${NC}"

# 0. Parse arguments
VERBOSE=0
QUIET_OPT="--quiet"
if [[ "${1:-}" == "--verbose" || "${1:-}" == "-v" ]]; then
  VERBOSE=1
  QUIET_OPT=""
fi

# 0. Enforce sudo and fix user environment
if [ "$EUID" -ne 0 ]; then
  echo -e "\n${RED}[ERROR] This script requires elevated privileges to install global dependencies (npm/cargo)."
  echo -e "Please run the installer with sudo:"
  echo -e "  sudo ./setup.sh${NC}\n"
  exit 1
fi

if [ -n "${SUDO_USER:-}" ]; then
  REAL_USER="$SUDO_USER"
  REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
  export HOME="$REAL_HOME"
  export USER="$REAL_USER"
  # Also override some env vars to prevent uv/cargo from defaulting to /root
  export CARGO_HOME="$REAL_HOME/.cargo"
  export UV_TOOL_DIR="$REAL_HOME/.local/share/uv/tools"
fi

# Resolve the absolute path of this script (= repo root, works even if symlinked)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 0. Save WIZARD_AI_DIR so skills and wrappers can reference the repo portably
echo -e "\n${BLUE}[0/10] Registering Wizard-AI installation path...${NC}"
mkdir -p "$HOME/.config/wizard-ai"
cat > "$HOME/.config/wizard-ai/env" <<EOF
# Wizard-AI environment — auto-generated by setup.sh on $(date '+%Y-%m-%d')
# Do not edit manually; re-run setup.sh to update.
export WIZARD_AI_DIR="$SCRIPT_DIR"
export PATH="\$HOME/.local/bin:\$PATH"
EOF

# Source the env file in the user's shell config if not already present
for RC in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
  if [[ -f "$RC" ]] && ! grep -q "wizard-ai/env" "$RC"; then
    echo "" >> "$RC"
    echo "# Wizard-AI — load environment (added by setup.sh)" >> "$RC"
    echo 'source "$HOME/.config/wizard-ai/env"' >> "$RC"
    echo -e "  ${GREEN}✓ Added source line to $RC${NC}"
  fi
done
# Export for the current session
export WIZARD_AI_DIR="$SCRIPT_DIR"
export PATH="$HOME/.local/bin:$PATH"
echo -e "${GREEN}✓ WIZARD_AI_DIR=\"$WIZARD_AI_DIR\"${NC}"

# 1. Check/Install UV
echo -e "\n${BLUE}[1/10] Checking for modern Python & Package Manager (uv)...${NC}"
if ! command -v uv &>/dev/null; then
  echo -e "${YELLOW}uv not found. Installing uv via official script...${NC}"
  # SECURITY: Executing scripts directly from the internet via pipe is a security risk.
  # Ideally, verify the hash before execution in a production environment.
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
else
  echo -e "${GREEN}✓ uv is already installed: $(uv --version)${NC}"
fi

# Ensure local directories exist
mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.ai-skills"

# 2. Recreate Python Virtual Environment for wrappers
echo -e "\n${BLUE}[2/10] Preparing Python Virtual Environment for LLMLingua & FlashRank...${NC}"
uv venv "$HOME/.ai-skills/venv" --seed $QUIET_OPT
VENV_PYTHON="$HOME/.ai-skills/venv/bin/python"

# Auto-install system dependencies for turbovec if possible
echo -e "${YELLOW}Checking system dependencies (Rust/Cargo & OpenBLAS) for turbovec...${NC}"
if command -v apt-get &>/dev/null; then
  if ! dpkg -s libopenblas-dev &>/dev/null || ! command -v cargo &>/dev/null; then
    echo -e "${YELLOW}Installing libopenblas-dev and cargo via apt-get...${NC}"
    apt-get update -yqq && apt-get install -yqq cargo libopenblas-dev
  fi
elif command -v pacman &>/dev/null; then
  if ! pacman -Qs openblas &>/dev/null || ! command -v cargo &>/dev/null; then
    echo -e "${YELLOW}Installing openblas and rust via pacman...${NC}"
    pacman -Sy --noconfirm rust openblas
  fi
elif command -v dnf &>/dev/null; then
  if ! rpm -q openblas-devel &>/dev/null || ! command -v cargo &>/dev/null; then
    echo -e "${YELLOW}Installing openblas-devel and cargo via dnf...${NC}"
    dnf install -y cargo openblas-devel
  fi
elif command -v brew &>/dev/null; then
  if ! sudo -u "$REAL_USER" brew list openblas &>/dev/null || ! command -v cargo &>/dev/null; then
    echo -e "${YELLOW}Installing openblas and rust via brew...${NC}"
    sudo -u "$REAL_USER" brew install rust openblas
  fi
fi

echo -e "${YELLOW}Installing llmlingua, flashrank, and turbovec inside the venv...${NC}"
uv pip install $QUIET_OPT --python "$VENV_PYTHON" \
  llmlingua flashrank transformers torch accelerate "aisuite[all]" \
  "git+https://github.com/RyanCodrai/turbovec.git#subdirectory=turbovec-python" \
  || {
       echo -e "${RED}❌ Failed to install Python dependencies. Se turbovec fallisce, potresti non avere i compilatori C++/Rust o OpenBLAS installati.${NC}"
       echo -e "${RED}Per favore installa: rust (cargo) e openblas prima di eseguire lo script, es:${NC}"
       echo -e "${RED}Arch: sudo pacman -S rust openblas${NC}"
       echo -e "${RED}Ubuntu: sudo apt install cargo libopenblas-dev${NC}"
       exit 1
     }
echo -e "${GREEN}✓ Virtual environment ready at ~/.ai-skills/venv/${NC}"

# 3. Setting up external git skill repositories
echo -e "\n${BLUE}[3/10] Setting up external git skill repositories...${NC}"

clone_skill_repo() {
  local url="$1"
  local dest_name="$2"
  local dest_dir="$HOME/.ai-skills/$dest_name"
  
  if [ ! -d "$dest_dir" ]; then
    echo -e "${YELLOW}Cloning $dest_name from GitHub...${NC}"
    git clone --depth 1 $QUIET_OPT "$url" "$dest_dir" || true
    echo -e "${GREEN}  ✓ $dest_name cloned.${NC}"
  else
    echo -e "${GREEN}✓ $dest_name is already present.${NC}"
  fi
}
clone_skill_repo "https://github.com/thedotmack/claude-mem.git" "claude-mem"
clone_skill_repo "https://github.com/chopratejas/headroom.git" "headroom"
clone_skill_repo "https://github.com/antvis/Infographic.git" "Infographic"
clone_skill_repo "https://github.com/mukul975/Anthropic-Cybersecurity-Skills.git" "cybersecurity-skills"
clone_skill_repo "https://github.com/AgriciDaniel/claude-blog.git" "claude-blog"
clone_skill_repo "https://github.com/AgriciDaniel/claude-seo.git" "claude-seo"
clone_skill_repo "https://github.com/google-labs-code/stitch-skills.git" "stitch-skills"
clone_skill_repo "https://github.com/google-labs-code/design.md.git" "design.md"
clone_skill_repo "https://github.com/SpinaBuilds/goodcode.git" "goodcode"

echo -e "\n${BLUE}Installing ECC, caveman, and design.md via NPM globally...${NC}"
if command -v npm &>/dev/null; then
  npm install -g ecc-universal
  npm install -g https://github.com/JuliusBrussee/caveman.git
  npm install -g @google/design.md
else
  echo -e "${YELLOW}NPM not found. Falling back to git clone for ECC, caveman and design.md...${NC}"
  clone_skill_repo "https://github.com/affaan-m/ECC.git" "ECC"
  clone_skill_repo "https://github.com/JuliusBrussee/caveman.git" "caveman"
fi

# 4. Install UV Global Tools
echo -e "\n${BLUE}[4/10] Installing global CLI Tools via uv tool...${NC}"

install_uv_tool() {
  local tool="$1"
  local pkg="${2:-$1}"   # optional package name if different from tool name
  echo -e "${YELLOW}Installing/Updating $tool...${NC}"
  
  local exit_code=0
  if [ "$VERBOSE" -eq 1 ]; then
    uv tool install --force "$pkg" || exit_code=$?
  else
    uv tool install --force "$pkg" &>/dev/null || exit_code=$?
  fi
  
  if [ $exit_code -eq 0 ]; then
    echo -e "${GREEN}  ✓ $tool installed.${NC}"
  else
    echo -e "${RED}  ⚠ Failed to install $tool (exit code $exit_code). You may need to install C++/Rust Build Tools.${NC}"
  fi
}

install_uv_tool "graphify"    "graphifyy"
install_uv_tool "litellm"
install_uv_tool "markitdown"
install_uv_tool "sqz"
install_uv_tool "headroom"    "headroom-ai"

# Install serena (semantic code intelligence — available via uvx)
echo -e "${YELLOW}Checking serena (semantic code search)...${NC}"
if ! command -v serena &>/dev/null; then
  if [ "$VERBOSE" -eq 1 ]; then
    uv tool install --force serena-agent || true
  else
    uv tool install --force serena-agent &>/dev/null || true
  fi
  # Verify installation
  if command -v serena &>/dev/null; then
    echo -e "${GREEN}  ✓ serena installed.${NC}"
  else
    echo -e "${RED}  ❌ failed to install serena.${NC}"
  fi
else
  echo -e "${GREEN}✓ serena already installed.${NC}"
fi

# Install lean-ctx (context intelligence binary)
echo -e "${YELLOW}Checking lean-ctx (context intelligence)...${NC}"
if command -v lean-ctx &>/dev/null; then
  echo -e "${GREEN}✓ lean-ctx already installed.${NC}"
else
  # Pre-flight check for node/npm
  if command -v npm &>/dev/null; then
    echo -e "${BLUE}  NPM detected, installing lean-ctx-bin...${NC}"
    if npm install -g lean-ctx-bin 2>/dev/null; then
      echo -e "${GREEN}  ✓ lean-ctx installed via npm.${NC}"
    elif npm install -g lean-ctx-bin --prefix ~/.local 2>/dev/null; then
      echo -e "${GREEN}  ✓ lean-ctx installed via npm locally (~/.local/bin).${NC}"
    elif command -v cargo &>/dev/null; then
      echo -e "${YELLOW}  ⚠ npm installation failed. Falling back to Cargo...${NC}"
      cargo install lean-ctx && echo -e "${GREEN}  ✓ lean-ctx installed via cargo.${NC}" || echo -e "${RED}  ✗ lean-ctx installation failed.${NC}"
    else
      echo -e "${RED}  ✗ lean-ctx installation via npm failed and Cargo is not available.${NC}"
      echo -e "${YELLOW}  Suggestion: run 'sudo npm install -g lean-ctx-bin' manually.${NC}"
    fi
  elif command -v cargo &>/dev/null; then
    echo -e "${BLUE}  NPM not found, but Cargo detected. Installing via Cargo...${NC}"
    cargo install lean-ctx && echo -e "${GREEN}  ✓ lean-ctx installed via cargo.${NC}" || echo -e "${RED}  ✗ lean-ctx installation failed.${NC}"
  else
    echo -e "${YELLOW}  ⚠ lean-ctx requires Node.js (npm) or Rust (cargo). Neither found.${NC}"
    echo -e "  Please install Node.js (https://nodejs.org) to enable context intelligence."
  fi
fi

# 5. Fix sqz binary (pre-compiled native binary for token compression)
echo -e "\n${BLUE}[5/10] Placing pre-compiled sqz binary...${NC}"
ARCH=$(uname -m)
SQZ_VER="v1.0.5"
SQZ_URL=""

case "$ARCH" in
  x86_64)
    SQZ_URL="https://github.com/ojuschugh1/sqz/releases/download/${SQZ_VER}/sqz-${SQZ_VER}-x86_64-unknown-linux-musl.tar.gz"
    ;;
  aarch64|arm64)
    SQZ_URL="https://github.com/ojuschugh1/sqz/releases/download/${SQZ_VER}/sqz-${SQZ_VER}-aarch64-unknown-linux-musl.tar.gz"
    ;;
  *)
    echo -e "${RED}✗ Unsupported architecture ($ARCH) for sqz binary. Compile sqz manually.${NC}"
    ;;
esac

if [ -n "$SQZ_URL" ]; then
  echo -e "${YELLOW}Fetching compiled sqz ${SQZ_VER} binary for $ARCH...${NC}"
  TMP_DIR=$(mktemp -d)
  curl -L -s "$SQZ_URL" -o "$TMP_DIR/sqz.tar.gz"
  tar -xzf "$TMP_DIR/sqz.tar.gz" -C "$TMP_DIR/"

  # Try to place in uv tool site-packages first, fallback to ~/.local/bin
  SQZ_BIN_DIR="$HOME/.local/share/uv/tools/sqz/lib"
  PYTHON_DIR=$(find "$SQZ_BIN_DIR" -maxdepth 2 -type d \
    -name "site-packages" 2>/dev/null | head -n 1 || true)

  if [ -n "$PYTHON_DIR" ]; then
    mkdir -p "$PYTHON_DIR/sqz/_bin"
    cp -f "$TMP_DIR/sqz" "$PYTHON_DIR/sqz/_bin/sqz"
    chmod +x "$PYTHON_DIR/sqz/_bin/sqz"
    echo -e "${GREEN}✓ sqz binary placed in Python site-packages ($ARCH).${NC}"
  else
    cp -f "$TMP_DIR/sqz" "$HOME/.local/bin/sqz"
    chmod +x "$HOME/.local/bin/sqz"
    echo -e "${YELLOW}⚠ sqz binary placed in ~/.local/bin/sqz (fallback).${NC}"
  fi
  rm -rf "$TMP_DIR"
fi

# 6. Copy and configure CLI Wrappers
echo -e "\n${BLUE}[6/10] Deploying custom AI CLI wrappers to ~/.local/bin/...${NC}"
cp -p "$SCRIPT_DIR"/bin/* "$HOME/.local/bin/" 2>/dev/null || true
chmod +x "$HOME/.local/bin"/ai-* 2>/dev/null || true
chmod +x "$HOME/.local/bin"/book-to-skill 2>/dev/null || true
# Create symlink for gemini-usage pointing to ai-usage to avoid duplicate script files
ln -sf ai-usage "$HOME/.local/bin/gemini-usage"
echo -e "${GREEN}✓ $(ls "$SCRIPT_DIR/bin/" | wc -l) wrapper scripts installed to ~/.local/bin/ (with gemini-usage symlinked)${NC}"

# 7. Install Skills for all agents
echo -e "\n${BLUE}[7/10] Installing AI agent skills...${NC}"
mkdir -p "$HOME/.gemini/config/skills"
cp -r "$SCRIPT_DIR"/skills/. "$HOME/.gemini/config/skills/"
echo -e "${GREEN}✓ $(ls "$SCRIPT_DIR/skills/" | wc -l) skills installed to ~/.gemini/config/skills/${NC}"

echo -e "${YELLOW}Syncing skills to Claude Code, Amp, and other agents...${NC}"
"$HOME/.local/bin/ai-sync-skills"

# 8. Git & NPM Credentials Setup (Optional for Contributors)
echo -e "\n${BLUE}[8/10] Git & NPM Credentials Setup (Optional for Contributors)...${NC}"
echo -e "${YELLOW}Do you want to configure your GitHub & NPM credentials now? (e.g. for publishing or contributing) [y/N]${NC}"
read -p "> " CONFIRM_CREDS
if [[ "$CONFIRM_CREDS" =~ ^[Yy]$ ]]; then
  # NPM Token
  echo -e "${CYAN}Please enter your NPM Publishing Token (or press enter to skip):${NC}"
  read -s -p "> " USER_NPM_TOKEN
  echo ""
  if [ -n "$USER_NPM_TOKEN" ]; then
    echo "//registry.npmjs.org/:_authToken=$USER_NPM_TOKEN" >> "$HOME/.npmrc"
    if ! grep -q "NPM_TOKEN" "$HOME/.config/wizard-ai/env"; then
      echo "export NPM_TOKEN=\"$USER_NPM_TOKEN\"" >> "$HOME/.config/wizard-ai/env"
    else
      sed -i "s|export NPM_TOKEN=.*|export NPM_TOKEN=\"$USER_NPM_TOKEN\"|" "$HOME/.config/wizard-ai/env"
    fi
    echo -e "  ${GREEN}✓ NPM Token registered.${NC}"
  fi

  # GitHub Token
  echo -e "${CYAN}Please enter your GitHub Personal Access Token (or press enter to skip):${NC}"
  read -s -p "> " USER_GH_TOKEN
  echo ""
  if [ -n "$USER_GH_TOKEN" ]; then
    if ! grep -q "GITHUB_TOKEN" "$HOME/.config/wizard-ai/env"; then
      echo "export GITHUB_TOKEN=\"$USER_GH_TOKEN\"" >> "$HOME/.config/wizard-ai/env"
    else
      sed -i "s|export GITHUB_TOKEN=.*|export GITHUB_TOKEN=\"$USER_GH_TOKEN\"|" "$HOME/.config/wizard-ai/env"
    fi
    if command -v gh &>/dev/null; then
      echo "$USER_GH_TOKEN" | env -u GITHUB_TOKEN gh auth login --with-token 2>/dev/null && \
        echo -e "  ${GREEN}✓ Logged in to GitHub CLI successfully.${NC}" || \
        echo -e "  ${YELLOW}⚠ Could not log in via gh CLI with the provided token.${NC}"
    fi
    echo -e "  ${GREEN}✓ GitHub Token registered.${NC}"
  fi
fi

# 9. Auto-Update Configuration
echo -e "\n${BLUE}[9/10] Auto-Update Configuration...${NC}"
echo -e "${YELLOW}Do you want to enable automatic background updates at system boot? [Y/n] (Auto-yes in 10s)${NC}"

ENABLE_UPDATE="Y"
read -t 10 -p "> " USER_INPUT || true
if [ -n "$USER_INPUT" ]; then
  ENABLE_UPDATE="$USER_INPUT"
fi

if [[ "$ENABLE_UPDATE" =~ ^[Yy]$ ]]; then
  echo -e "${GREEN}✓ Enabling automatic background updates at boot...${NC}"
  if command -v crontab &>/dev/null; then
    CRON_CMD="@reboot $HOME/.local/bin/ai-update --quiet"
    (crontab -u "$USER" -l 2>/dev/null | grep -v "ai-update" ; echo "$CRON_CMD") | crontab -u "$USER" -
    echo -e "${GREEN}  ✓ Cronjob installed for user $USER.${NC}"
  elif command -v systemctl &>/dev/null; then
    echo -e "${BLUE}  i  cron not found. Setting up systemd user service instead...${NC}"
    mkdir -p "$HOME/.config/systemd/user"
    cat > "$HOME/.config/systemd/user/ai-update.service" <<EOF
[Unit]
Description=Wizard-AI Auto Update
After=network-online.target

[Service]
Type=oneshot
ExecStart=$HOME/.local/bin/ai-update --quiet

[Install]
WantedBy=default.target
EOF
    chown -R "$USER:$USER" "$HOME/.config/systemd"
    REAL_UID=$(id -u "$USER")
    sudo -u "$USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user daemon-reload || true
    sudo -u "$USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user enable ai-update.service || true
    echo -e "${GREEN}  ✓ systemd service installed for user $USER.${NC}"
  else
    echo -e "${RED}⚠ cron and systemctl not found. Auto-updates cannot be configured.${NC}"
  fi
else
  echo -e "${YELLOW}  Auto-updates disabled. Update manually using 'ai-update'.${NC}"
  if command -v crontab &>/dev/null; then
    crontab -u "$USER" -l 2>/dev/null | grep -v "ai-update" | crontab -u "$USER" - || true
  fi
fi

# 10. Fix ownership if run via sudo
if [ -n "${SUDO_USER:-}" ]; then
  echo -e "\n${BLUE}[10/10] Fixing file ownership for user $USER...${NC}"
  chown -R "$USER:$USER" "$HOME/.config/wizard-ai" "$HOME/.local/bin" "$HOME/.local/share/uv" "$HOME/.ai-skills" "$HOME/.gemini" "$HOME/.cargo" 2>/dev/null || true
fi

# 9. Final summary
echo -e "\n${GREEN}============================================================"
echo -e "     🎉  Wizard-AI Environment Installed Successfully! 🎉"
echo -e "============================================================${NC}"
echo -e "\nAvailable commands in your terminal:"
echo -e "  ${CYAN}ai-help${NC}      - Central hub for all AI commands"
echo -e "  ${CYAN}ai-usage${NC}     - View Gemini usage statistics and token budget"
echo -e "  ${CYAN}ai-graph${NC}     - Run Graphify to map codebases to knowledge graphs"
echo -e "  ${CYAN}ai-compress${NC}  - Compress prompt context via LLMLingua (up to 20x)"
echo -e "  ${CYAN}ai-rerank${NC}    - Re-rank list components for RAG via FlashRank"
echo -e "  ${CYAN}ai-squeeze${NC}   - Compress CLI outputs / files via Sqz"
echo -e "  ${CYAN}ai-convert${NC}   - Extract clean Markdown from PDF, DOCX, images, etc."
echo -e "  ${CYAN}ai-mem${NC}       - Access persistent semantic memory (claude-mem)"
echo -e "  ${CYAN}ai-design${NC}    - Browse & apply DESIGN.md files for UI generation"
echo -e "  ${CYAN}ai-taste${NC}     - Apply anti-slop frontend design skill"
echo -e "  ${CYAN}ai-lean${NC}      - Lean Context Intelligence (60-90% token savings)"
echo -e "  ${CYAN}ai-caveman${NC}   - Cut output tokens by ~75% while keeping accuracy"
echo -e "  ${CYAN}ai-scaffold${NC}  - Scaffold Express/Nuxt projects from templates"
echo -e "  ${CYAN}ai-quota${NC}     - View AI provider quotas and subscriptions"
echo -e "  ${CYAN}ai-sync-skills${NC} - Sync skills across all AI agents"
echo -e ""
echo -e "${YELLOW}Important: Reload your shell to activate the environment:${NC}"
echo -e "  ${PURPLE}source ~/.bashrc${NC}  (or restart your terminal)"
echo -e ""
echo -e "${YELLOW}Your Wizard-AI directory:${NC} ${PURPLE}$WIZARD_AI_DIR${NC}"
echo -e "${YELLOW}Skills:${NC} ${PURPLE}~/.gemini/config/skills/${NC}"
echo -e "${YELLOW}CLIs:${NC}   ${PURPLE}~/.local/bin/${NC}"
echo -e ""
echo -e "${CYAN}Run 'ai-help' to see all available tools and their usage.${NC}"
