#!/usr/bin/env bash
# setup.sh — Automated installation and setup script for the Wizard-AI environment.
# Supported Platform: Linux (x86_64 / aarch64) | macOS (x86_64 / arm64)
#
# After installation, the variable $WIZARD_AI_DIR is available in your shell
# and points to the directory where you cloned this repository.

set -euo pipefail

# ANSI color codes for premium terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}============================================================"
echo -e "         🧙‍♂️  Wizard-AI Environment Setup Wizard"
echo -e "============================================================${NC}"

# Resolve the absolute path of this script (= repo root, works even if symlinked)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 0. Save WIZARD_AI_DIR so skills and wrappers can reference the repo portably
echo -e "\n${BLUE}[0/8] Registering Wizard-AI installation path...${NC}"
mkdir -p "$HOME/.config/wizard-ai"
cat > "$HOME/.config/wizard-ai/env" <<EOF
# Wizard-AI environment — auto-generated by setup.sh on $(date '+%Y-%m-%d')
# Do not edit manually; re-run setup.sh to update.
export WIZARD_AI_DIR="$SCRIPT_DIR"
export PATH="\$HOME/.local/bin:\$PATH"
EOF

# Source the env file in the user's shell config if not already present
for RC in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
  if [[ -f "$RC" ]] && ! grep -q "wizard-ai/env" "$RC"; then
    echo "" >> "$RC"
    echo "# Wizard-AI — load environment (added by setup.sh)" >> "$RC"
    echo 'source "$HOME/.config/wizard-ai/env"' >> "$RC"
    echo -e "  ${GREEN}✓ Added source line to $RC${NC}"
  fi
done
# Export for the current session
export WIZARD_AI_DIR="$SCRIPT_DIR"
export PATH="$HOME/.local/bin:$PATH"
echo -e "${GREEN}✓ WIZARD_AI_DIR=\"$WIZARD_AI_DIR\"${NC}"

# 1. Check/Install UV
echo -e "\n${BLUE}[1/8] Checking for modern Python & Package Manager (uv)...${NC}"
if ! command -v uv &>/dev/null; then
  echo -e "${YELLOW}uv not found. Installing uv via official script...${NC}"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
else
  echo -e "${GREEN}✓ uv is already installed: $(uv --version)${NC}"
fi

# Ensure local directories exist
mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.ai-skills"

# 2. Recreate Python Virtual Environment for wrappers
echo -e "\n${BLUE}[2/8] Preparing Python Virtual Environment for LLMLingua & FlashRank...${NC}"
uv venv "$HOME/.ai-skills/venv" --seed --quiet
VENV_PYTHON="$HOME/.ai-skills/venv/bin/python"
echo -e "${YELLOW}Installing llmlingua and flashrank inside the venv...${NC}"
uv pip install --quiet --python "$VENV_PYTHON" llmlingua flashrank
echo -e "${GREEN}✓ Virtual environment ready at ~/.ai-skills/venv/${NC}"

# 3. Clone and install required skill repositories if not present
echo -e "\n${BLUE}[3/8] Setting up external git skill repositories in ~/.ai-skills/...${NC}"

clone_if_missing() {
  local name="$1"
  local url="$2"
  local dest="$HOME/.ai-skills/$name"
  if [ ! -d "$dest" ]; then
    echo -e "${YELLOW}Cloning $name...${NC}"
    git clone --quiet "$url" "$dest"
    echo -e "${GREEN}  ✓ $name cloned.${NC}"
  else
    echo -e "${GREEN}✓ $name already present.${NC}"
  fi
}

clone_if_missing "claude-mem"       "https://github.com/thedotmack/claude-mem"
clone_if_missing "geminiusage"      "https://github.com/rmedranollamas/geminiusage.git"
clone_if_missing "book-to-skill"    "https://github.com/virgiliojr94/book-to-skill.git"
clone_if_missing "ECC"              "https://github.com/affaan-m/ECC.git"
clone_if_missing "wiki-brain-skill" "https://github.com/tenfoldmarc/wiki-brain-skill"
clone_if_missing "cockpit-tools"    "https://github.com/jlcodes99/cockpit-tools.git"
clone_if_missing "awesome-design-md" "https://github.com/VoltAgent/awesome-design-md.git"
clone_if_missing "taste-skill"       "https://github.com/leonxlnx/taste-skill.git"
clone_if_missing "spec-kit"          "https://github.com/github/spec-kit.git"
clone_if_missing "lean-ctx"          "https://github.com/yvgude/lean-ctx.git"
clone_if_missing "rtk"               "https://github.com/rtk-ai/rtk.git"
clone_if_missing "nuxt"              "https://github.com/nuxt/nuxt.git"
clone_if_missing "express-typescript-starter" "https://github.com/ToniR7/express-typescript-starter.git"

# Install claude-mem Python package if setup.py/pyproject.toml is present
if [ -f "$HOME/.ai-skills/claude-mem/pyproject.toml" ] || \
   [ -f "$HOME/.ai-skills/claude-mem/setup.py" ]; then
  uv pip install --quiet --python "$VENV_PYTHON" \
    -e "$HOME/.ai-skills/claude-mem" || true
fi

# 4. Install UV Global Tools
echo -e "\n${BLUE}[4/8] Installing global CLI Tools via uv tool...${NC}"

install_uv_tool() {
  local tool="$1"
  local pkg="${2:-$1}"   # optional package name if different from tool name
  echo -e "${YELLOW}Installing/Updating $tool...${NC}"
  uv tool install --force "$pkg" &>/dev/null || true
  echo -e "${GREEN}  ✓ $tool installed.${NC}"
}

install_uv_tool "graphify"    "graphifyy"
install_uv_tool "litellm"
install_uv_tool "markitdown"
install_uv_tool "sqz"

# Install serena (semantic code intelligence — available via uvx)
echo -e "${YELLOW}Checking serena (semantic code search)...${NC}"
if ! command -v serena &>/dev/null; then
  uv tool install --force serena &>/dev/null || true
  echo -e "${GREEN}  ✓ serena installed.${NC}"
else
  echo -e "${GREEN}✓ serena already installed.${NC}"
fi

# Install lean-ctx (context intelligence binary)
echo -e "${YELLOW}Checking lean-ctx (context intelligence)...${NC}"
if command -v lean-ctx &>/dev/null; then
  echo -e "${GREEN}✓ lean-ctx already installed.${NC}"
else
  # Pre-flight check for node/npm
  if command -v npm &>/dev/null; then
    echo -e "${BLUE}  NPM detected, installing lean-ctx-bin...${NC}"
    npm install -g lean-ctx-bin 2>/dev/null && echo -e "${GREEN}  ✓ lean-ctx installed via npm.${NC}" || \
      echo -e "${RED}  ✗ lean-ctx installation via npm failed.${NC}"
  elif command -v cargo &>/dev/null; then
    echo -e "${BLUE}  NPM not found, but Cargo detected. You can install lean-ctx via Cargo:${NC}"
    echo -e "  ${CYAN}cargo install lean-ctx${NC}"
  else
    echo -e "${YELLOW}  ⚠ lean-ctx requires Node.js (npm) or Rust (cargo). Neither found.${NC}"
    echo -e "  Please install Node.js (https://nodejs.org) to enable context intelligence."
  fi
fi

# 5. Fix sqz binary (pre-compiled native binary for token compression)
echo -e "\n${BLUE}[5/8] Placing pre-compiled sqz binary...${NC}"
ARCH=$(uname -m)
SQZ_VER="v1.0.5"
SQZ_URL=""

case "$ARCH" in
  x86_64)
    SQZ_URL="https://github.com/ojuschugh1/sqz/releases/download/${SQZ_VER}/sqz-${SQZ_VER}-x86_64-unknown-linux-musl.tar.gz"
    ;;
  aarch64|arm64)
    SQZ_URL="https://github.com/ojuschugh1/sqz/releases/download/${SQZ_VER}/sqz-${SQZ_VER}-aarch64-unknown-linux-musl.tar.gz"
    ;;
  *)
    echo -e "${RED}✗ Unsupported architecture ($ARCH) for sqz binary. Compile sqz manually.${NC}"
    ;;
esac

if [ -n "$SQZ_URL" ]; then
  echo -e "${YELLOW}Fetching compiled sqz ${SQZ_VER} binary for $ARCH...${NC}"
  TMP_DIR=$(mktemp -d)
  curl -L -s "$SQZ_URL" -o "$TMP_DIR/sqz.tar.gz"
  tar -xzf "$TMP_DIR/sqz.tar.gz" -C "$TMP_DIR/"

  # Try to place in uv tool site-packages first, fallback to ~/.local/bin
  SQZ_BIN_DIR="$HOME/.local/share/uv/tools/sqz/lib"
  PYTHON_DIR=$(find "$SQZ_BIN_DIR" -maxdepth 2 -type d \
    -name "site-packages" 2>/dev/null | head -n 1 || true)

  if [ -n "$PYTHON_DIR" ]; then
    mkdir -p "$PYTHON_DIR/sqz/_bin"
    cp -f "$TMP_DIR/sqz" "$PYTHON_DIR/sqz/_bin/sqz"
    chmod +x "$PYTHON_DIR/sqz/_bin/sqz"
    echo -e "${GREEN}✓ sqz binary placed in Python site-packages ($ARCH).${NC}"
  else
    cp -f "$TMP_DIR/sqz" "$HOME/.local/bin/sqz"
    chmod +x "$HOME/.local/bin/sqz"
    echo -e "${YELLOW}⚠ sqz binary placed in ~/.local/bin/sqz (fallback).${NC}"
  fi
  rm -rf "$TMP_DIR"
fi

# 6. Copy and configure CLI Wrappers
echo -e "\n${BLUE}[6/8] Deploying custom AI CLI wrappers to ~/.local/bin/...${NC}"
cp -p "$SCRIPT_DIR"/bin/* "$HOME/.local/bin/"
chmod +x "$HOME/.local/bin"/ai-* 2>/dev/null || true
chmod +x "$HOME/.local/bin"/book-to-skill 2>/dev/null || true
# Create symlink for gemini-usage pointing to ai-usage to avoid duplicate script files
ln -sf ai-usage "$HOME/.local/bin/gemini-usage"
echo -e "${GREEN}✓ $(ls "$SCRIPT_DIR/bin/" | wc -l) wrapper scripts installed to ~/.local/bin/ (with gemini-usage symlinked)${NC}"

# 7. Install Skills for all agents
echo -e "\n${BLUE}[7/8] Installing AI agent skills...${NC}"
mkdir -p "$HOME/.gemini/config/skills"
cp -r "$SCRIPT_DIR"/skills/. "$HOME/.gemini/config/skills/"
echo -e "${GREEN}✓ $(ls "$SCRIPT_DIR/skills/" | wc -l) skills installed to ~/.gemini/config/skills/${NC}"

echo -e "${YELLOW}Syncing skills to Claude Code, Amp, and other agents...${NC}"
"$HOME/.local/bin/ai-sync-skills"

# 8. Final summary
echo -e "\n${GREEN}============================================================"
echo -e "     🎉  Wizard-AI Environment Installed Successfully! 🎉"
echo -e "============================================================${NC}"
echo -e "\nAvailable commands in your terminal:"
echo -e "  ${CYAN}ai-help${NC}      - Central hub for all AI commands"
echo -e "  ${CYAN}ai-usage${NC}     - View Gemini usage statistics and token budget"
echo -e "  ${CYAN}ai-graph${NC}     - Run Graphify to map codebases to knowledge graphs"
echo -e "  ${CYAN}ai-compress${NC}  - Compress prompt context via LLMLingua (up to 20x)"
echo -e "  ${CYAN}ai-rerank${NC}    - Re-rank list components for RAG via FlashRank"
echo -e "  ${CYAN}ai-squeeze${NC}   - Compress CLI outputs / files via Sqz"
echo -e "  ${CYAN}ai-convert${NC}   - Extract clean Markdown from PDF, DOCX, images, etc."
echo -e "  ${CYAN}ai-mem${NC}       - Access persistent semantic memory (claude-mem)"
echo -e "  ${CYAN}ai-design${NC}    - Browse & apply DESIGN.md files for UI generation"
echo -e "  ${CYAN}ai-taste${NC}     - Apply anti-slop frontend design skill"
echo -e "  ${CYAN}ai-lean${NC}      - Lean Context Intelligence (60-90% token savings)"
echo -e "  ${CYAN}ai-scaffold${NC}  - Scaffold Express/Nuxt projects from templates"
echo -e "  ${CYAN}ai-quota${NC}     - View AI provider quotas and subscriptions"
echo -e "  ${CYAN}ai-sync-skills${NC} - Sync skills across all AI agents"
echo -e ""
echo -e "${YELLOW}Important: Reload your shell to activate the environment:${NC}"
echo -e "  ${PURPLE}source ~/.bashrc${NC}  (or restart your terminal)"
echo -e ""
echo -e "${YELLOW}Your Wizard-AI directory:${NC} ${PURPLE}$WIZARD_AI_DIR${NC}"
echo -e "${YELLOW}Skills:${NC} ${PURPLE}~/.gemini/config/skills/${NC}"
echo -e "${YELLOW}CLIs:${NC}   ${PURPLE}~/.local/bin/${NC}"
echo -e ""
echo -e "${CYAN}Run 'ai-help' to see all available tools and their usage.${NC}"
