# setup.ps1 — Automated installation and setup script for the Wizard-AI environment.
# Supported Platform: Windows 10/11 (x86_64) — native PowerShell port of setup.sh
#
# Usage:  powershell -ExecutionPolicy Bypass -File setup.ps1
#
# After installation, the WIZARD_AI_DIR user environment variable is available
# and points to the directory where you cloned this repository.
#
# Requirements: git on PATH. Everything else (uv, Python venv, tools) is
# installed automatically.

param (
    [switch]$VerboseMode
)

# PowerShell security hardening: Enforce TLS 1.2 and TLS 1.3 explicitly
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13

$QuietOpt = '--quiet'
if ($VerboseMode) {
    $QuietOpt = ''
    $VerbosePreference = 'Continue'
    $DebugPreference = 'Continue'
}

Write-Host '============================================================' -ForegroundColor Cyan
Write-Host '          Wizard-AI Environment Setup Wizard (Windows)' -ForegroundColor Cyan
Write-Host '============================================================' -ForegroundColor Cyan

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host '[X] git not found on PATH. Install Git for Windows first: https://git-scm.com/download/win' -ForegroundColor Red
    exit 1
}

# Resolve the absolute path of this script (= repo root)
$ScriptDir = $PSScriptRoot
$LocalBin = Join-Path $HOME '.local\bin'
$AiSkills = Join-Path $HOME '.ai-skills'

# 0. Save WIZARD_AI_DIR so skills and wrappers can reference the repo portably
Write-Host ''
Write-Host '[0/8] Registering Wizard-AI installation path...' -ForegroundColor Blue
$ConfigDir = Join-Path $HOME '.config\wizard-ai'
$null = New-Item -ItemType Directory -Force -Path $ConfigDir
$EnvFile = Join-Path $ConfigDir 'env.ps1'
$Stamp = Get-Date -Format 'yyyy-MM-dd'
@"
# Wizard-AI environment — auto-generated by setup.ps1 on $Stamp
# Do not edit manually; re-run setup.ps1 to update.
`$env:WIZARD_AI_DIR = '$ScriptDir'
if (`$env:Path -notlike "*$LocalBin*") { `$env:Path = "$LocalBin;`$(`$env:Path)" }
"@ | Set-Content -Path $EnvFile -Encoding utf8

# Persist as user environment variables (the Windows equivalent of ~/.bashrc)
[Environment]::SetEnvironmentVariable('WIZARD_AI_DIR', $ScriptDir, 'User')
$UserPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $UserPath) { $UserPath = '' }
if ($UserPath -notlike "*$LocalBin*") {
    [Environment]::SetEnvironmentVariable('Path', "$LocalBin;$UserPath", 'User')
    Write-Host "  [ok] Added $LocalBin to your user PATH" -ForegroundColor Green
}
# Export for the current session
$env:WIZARD_AI_DIR = $ScriptDir
if ($env:Path -notlike "*$LocalBin*") { $env:Path = "$LocalBin;$($env:Path)" }
Write-Host "[ok] WIZARD_AI_DIR=`"$ScriptDir`"" -ForegroundColor Green

# 1. Check/Install UV
Write-Host ''
Write-Host '[1/8] Checking for modern Python & Package Manager (uv)...' -ForegroundColor Blue
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Host 'uv not found. Installing uv via official script...' -ForegroundColor Yellow
    # SECURITY: Executing scripts directly from the internet via pipe is a security risk.
    # Ideally, download the script, verify its hash/signature, and then execute it.
    Invoke-RestMethod https://astral.sh/uv/install.ps1 | Invoke-Expression
    if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
        Write-Host '[X] uv installation failed. Install manually: https://docs.astral.sh/uv/' -ForegroundColor Red
        exit 1
    }
}
else {
    Write-Host "[ok] uv is already installed: $(uv --version)" -ForegroundColor Green
}

# Ensure local directories exist
$null = New-Item -ItemType Directory -Force -Path $LocalBin
$null = New-Item -ItemType Directory -Force -Path $AiSkills

# Optional: Install native Unix tools for Windows (ls, cp, grep, etc.)
Write-Host 'Checking for Microsoft.Coreutils...' -ForegroundColor Yellow
if (-not (Get-Command ls -ErrorAction SilentlyContinue | Where-Object { $_.Source -match "coreutils" })) {
    Write-Host '  > Command: winget install Microsoft.Coreutils --accept-package-agreements --accept-source-agreements --verbose-logs' -ForegroundColor DarkGray
    Write-Host '  > Note: If this hangs, check for hidden UAC prompts in your taskbar, or press Enter.' -ForegroundColor DarkGray
    winget install Microsoft.Coreutils --accept-package-agreements --accept-source-agreements --verbose-logs
    Write-Host '  > winget command finished.' -ForegroundColor DarkGray
}
else {
    Write-Host '[ok] Microsoft.Coreutils is already installed.' -ForegroundColor Green
}

# Ensure MSVC C++ Build Tools are installed for headroom-ai compilation
Write-Host 'Checking for MSVC C++ Build Tools...' -ForegroundColor Yellow
$VsWherePath = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
$HasMsvc = $false
if (Test-Path $VsWherePath) {
    $MsvcCheck = & $VsWherePath -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if ($MsvcCheck) { $HasMsvc = $true }
}
if (-not $HasMsvc) {
    Write-Host 'MSVC C++ Build Tools not found. Installing via winget (this may take a few minutes)...' -ForegroundColor Yellow
    Write-Host '  > Note: A UAC prompt may appear in the background for Visual Studio Installer. Please accept it.' -ForegroundColor Yellow
    $VsOverride = '--quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended'
    Write-Host "  > Command: winget install --id Microsoft.VisualStudio.2022.BuildTools --exact --force --accept-package-agreements --accept-source-agreements --override `"$VsOverride`" --verbose-logs" -ForegroundColor DarkGray
    winget install --id Microsoft.VisualStudio.2022.BuildTools --exact --force --accept-package-agreements --accept-source-agreements --override $VsOverride --verbose-logs
    Write-Host '  > winget command finished.' -ForegroundColor DarkGray
    Write-Host '[ok] MSVC C++ Build Tools installed.' -ForegroundColor Green
} else {
    Write-Host '[ok] MSVC C++ Build Tools are already installed.' -ForegroundColor Green
}

# 2. Recreate Python Virtual Environment for wrappers
Write-Host ''
Write-Host '[2/8] Preparing Python Virtual Environment for LLMLingua & FlashRank...' -ForegroundColor Blue
$VenvDir = Join-Path $AiSkills 'venv'
if ($QuietOpt) { uv venv $VenvDir --python 3.12 --seed --quiet } else { uv venv $VenvDir --python 3.12 --seed }
$VenvPython = Join-Path $VenvDir 'Scripts\python.exe'
Write-Host 'Installing llmlingua and flashrank inside the venv (this can take a while)...' -ForegroundColor Yellow
if ($QuietOpt) { uv pip install --quiet --python $VenvPython llmlingua flashrank "aisuite[all]" } else { uv pip install --python $VenvPython llmlingua flashrank "aisuite[all]" }
Write-Host "[ok] Virtual environment ready at $VenvDir" -ForegroundColor Green

# 3. Clone and install required skill repositories if not present
Write-Host ''
Write-Host "[3/8] Setting up external git skill repositories in $AiSkills..." -ForegroundColor Blue

function Clone-SkillRepo($Url, $DestName) {
    $DestDir = Join-Path $AiSkills $DestName
    if (-not (Test-Path $DestDir)) {
        Write-Host "Cloning $DestName from GitHub..." -ForegroundColor Yellow
        if ($QuietOpt) {
            git clone --depth 1 --quiet $Url $DestDir
        } else {
            git clone --depth 1 $Url $DestDir
        }
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  [!] $DestName clone failed" -ForegroundColor Red
        } else {
            Write-Host "  [ok] $DestName cloned." -ForegroundColor Green
        }
    } else {
        Write-Host "  [ok] $DestName is already present." -ForegroundColor Green
    }
}

Clone-SkillRepo 'https://github.com/thedotmack/claude-mem.git' 'claude-mem'
Clone-SkillRepo 'https://github.com/chopratejas/headroom.git' 'headroom'
Clone-SkillRepo 'https://github.com/antvis/Infographic.git' 'Infographic'
Clone-SkillRepo 'https://github.com/mukul975/Anthropic-Cybersecurity-Skills.git' 'cybersecurity-skills'

Write-Host "Installing ECC and caveman via NPM globally..." -ForegroundColor Yellow
if (Get-Command npm -ErrorAction SilentlyContinue) {
    npm install -g ecc-universal
    npm install -g https://github.com/JuliusBrussee/caveman.git
} else {
    Write-Host "NPM not found. Falling back to git clone for ECC and caveman..." -ForegroundColor Yellow
    Clone-SkillRepo 'https://github.com/affaan-m/ECC.git' 'ECC'
    Clone-SkillRepo 'https://github.com/JuliusBrussee/caveman.git' 'caveman'
}
Clone-SkillRepo 'https://github.com/yvgude/lean-ctx.git' 'lean-ctx'

# 4. Install UV Global Tools
Write-Host ''
Write-Host '[4/8] Installing global CLI Tools via uv tool...' -ForegroundColor Blue

function Install-UvTool($Tool, $Pkg) {
    if (-not $Pkg) { $Pkg = $Tool }
    Write-Host "Installing/Updating $Tool..." -ForegroundColor Yellow
    
    # Run uv tool install and capture stderr
    $err = $(uv tool install --force $Pkg 2>&1)
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  [ok] $Tool installed." -ForegroundColor Green
    } else {
        if ($Tool -eq 'headroom') {
            Write-Host "  [!] Failed to install $Tool (MSVC C++ Build Tools required). Skipping headroom setup, proceeding with the rest..." -ForegroundColor Yellow
        } else {
            Write-Host "  [!] Failed to install $Tool (exit code $LASTEXITCODE). You may need to install MSVC C++ Build Tools." -ForegroundColor Red
            Write-Host "      Details: $err" -ForegroundColor DarkGray
        }
    }
}

Install-UvTool 'graphify' 'graphifyy'
Install-UvTool 'litellm'
Install-UvTool 'markitdown'
Install-UvTool 'sqz'
Install-UvTool 'headroom' 'headroom-ai'

# Install serena (semantic code intelligence — available via uvx)
Write-Host 'Checking serena (semantic code search)...' -ForegroundColor Yellow
if (-not (Get-Command serena -ErrorAction SilentlyContinue)) {
    uv tool install --force serena-agent | Out-Null
    Write-Host '  [ok] serena installed.' -ForegroundColor Green
}
else {
    Write-Host '[ok] serena already installed.' -ForegroundColor Green
}

# 5. Fix sqz binary (pre-compiled native binary for token compression)
Write-Host ''
Write-Host '[5/8] Placing pre-compiled sqz binary...' -ForegroundColor Blue
$SqzVer = 'v1.0.5'
$Arch = $env:PROCESSOR_ARCHITECTURE

if ($Arch -eq 'AMD64') {
    $SqzUrl = "https://github.com/ojuschugh1/sqz/releases/download/$SqzVer/sqz-$SqzVer-x86_64-pc-windows-msvc.zip"
    Write-Host "Fetching compiled sqz $SqzVer binary for x86_64..." -ForegroundColor Yellow
    $TmpDir = Join-Path $env:TEMP ([guid]::NewGuid().ToString())
    $null = New-Item -ItemType Directory -Force -Path $TmpDir
    try {
        # Security Hardening: UseBasicParsing prevents IE DOM parsing vulnerabilities
        Invoke-WebRequest -Uri $SqzUrl -OutFile "$TmpDir\sqz.zip" -UseBasicParsing
        Expand-Archive -Path (Join-Path $TmpDir 'sqz.zip') -DestinationPath $TmpDir -Force
        $SqzExe = Get-ChildItem -Path $TmpDir -Recurse -Filter 'sqz.exe' | Select-Object -First 1

        if ($SqzExe) {
            # Try to place in uv tool site-packages first, fallback to ~\.local\bin
            $PlacedInSitePackages = $false
            $UvToolDir = (uv tool dir).Trim()
            $SqzToolDir = Join-Path $UvToolDir 'sqz'
            if (Test-Path $SqzToolDir) {
                $SitePackages = Get-ChildItem -Path $SqzToolDir -Recurse -Directory -Filter 'site-packages' -ErrorAction SilentlyContinue | Select-Object -First 1
                if ($SitePackages) {
                    $BinDir = Join-Path $SitePackages.FullName 'sqz\_bin'
                    $null = New-Item -ItemType Directory -Force -Path $BinDir
                    Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $BinDir 'sqz.exe') -Force
                    # Also without extension, in case the package wrapper looks for "sqz"
                    Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $BinDir 'sqz') -Force
                    Write-Host '[ok] sqz binary placed in Python site-packages (x86_64).' -ForegroundColor Green
                    $PlacedInSitePackages = $true
                }
            }
            if (-not $PlacedInSitePackages) {
                Copy-Item -Path $SqzExe.FullName -Destination (Join-Path $LocalBin 'sqz.exe') -Force
                Write-Host "[!] sqz binary placed in $LocalBin\sqz.exe (fallback)." -ForegroundColor Yellow
            }
        }
        else {
            Write-Host '[!] sqz.exe not found inside the release archive — skipping.' -ForegroundColor Yellow
        }
    }
    catch {
        Write-Host "[!] Could not download/extract sqz binary: $($_.Exception.Message)" -ForegroundColor Yellow
    }
    finally {
        Remove-Item -Path $TmpDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}
else {
    Write-Host "[X] No pre-compiled sqz Windows binary for architecture '$Arch'. Compile sqz manually." -ForegroundColor Red
}

# 6. Copy and configure CLI Wrappers
Write-Host ''
Write-Host "[6/8] Deploying custom AI CLI wrappers to $LocalBin..." -ForegroundColor Blue
$WrappersSrc = Join-Path $ScriptDir 'bin\windows'

# Security: Ensure paths are strictly within the project directory to prevent path traversal
$ResolvedSrc = Resolve-Path $WrappersSrc -ErrorAction SilentlyContinue
if (-not $ResolvedSrc -or -not $ResolvedSrc.Path.StartsWith($ScriptDir)) {
    Write-Host "[X] Invalid wrappers source path. Potential path traversal detected." -ForegroundColor Red
    exit 1
}

Copy-Item -Path (Join-Path $WrappersSrc '*.ps1') -Destination $LocalBin -Force
$null = New-Item -ItemType Directory -Force -Path (Join-Path $LocalBin 'lib')
Copy-Item -Path (Join-Path $WrappersSrc 'lib\*') -Destination (Join-Path $LocalBin 'lib') -Recurse -Force

# Generate .cmd shims so wrappers can be invoked as plain commands
# (e.g. "ai-help") from cmd.exe, PowerShell, and other AI agents.
function New-CmdShim($CommandName, $Ps1Name) {
    $ShimPath = Join-Path $LocalBin "$CommandName.cmd"
    $Content = "@echo off`r`npowershell -NoProfile -ExecutionPolicy Bypass -File `"%~dp0$Ps1Name`" %*"
    Set-Content -Path $ShimPath -Value $Content -Encoding Ascii
}

$Wrappers = Get-ChildItem -Path $WrappersSrc -Filter '*.ps1'
foreach ($W in $Wrappers) {
    New-CmdShim $W.BaseName $W.Name
}
# gemini-usage is an alias of ai-usage (same script, no duplicate files)
New-CmdShim 'gemini-usage' 'ai-usage.ps1'
Write-Host "[ok] $($Wrappers.Count) wrapper scripts installed to $LocalBin (with gemini-usage shim)" -ForegroundColor Green

# 7. Install Skills for all agents
Write-Host ''
Write-Host '[7/8] Installing AI agent skills...' -ForegroundColor Blue
$SkillsDst = Join-Path $HOME '.gemini\config\skills'
$null = New-Item -ItemType Directory -Force -Path $SkillsDst
Copy-Item -Path (Join-Path $ScriptDir 'skills\*') -Destination $SkillsDst -Recurse -Force
$SkillCount = (Get-ChildItem -Path (Join-Path $ScriptDir 'skills') -Directory | Measure-Object).Count
Write-Host "[ok] $SkillCount skills installed to $SkillsDst" -ForegroundColor Green

Write-Host 'Syncing skills to Claude Code, Amp, and other agents...' -ForegroundColor Yellow
& (Join-Path $LocalBin 'ai-sync-skills.ps1')

# 8. Auto-Update Configuration
Write-Host ''
Write-Host '[8/8] Auto-Update Configuration...' -ForegroundColor Blue
Write-Host 'Do you want to enable automatic background updates at system logon? [Y/n] (Auto-yes in 10s) ' -ForegroundColor Yellow -NoNewline

$EnableUpdate = 'Y'
$TimeoutSeconds = 10
$Watch = [System.Diagnostics.Stopwatch]::StartNew()
$Host.UI.RawUI.FlushInputBuffer()
while ($Watch.Elapsed.TotalSeconds -lt $TimeoutSeconds) {
    if ($Host.UI.RawUI.KeyAvailable) {
        $KeyInfo = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        if ($KeyInfo.Character -ne 0) {
            $Key = $KeyInfo.Character
            Write-Host $Key
            if ($Key -eq 'n' -or $Key -eq 'N') { $EnableUpdate = 'N' }
            break
        }
    }
    Start-Sleep -Milliseconds 100
}
if (-not $Host.UI.RawUI.KeyAvailable) { Write-Host '' }

$StartupFolder = [Environment]::GetFolderPath('Startup')
$StartupShortcut = Join-Path $StartupFolder "WizardAI-AutoUpdate.lnk"

if ($EnableUpdate -eq 'Y') {
    Write-Host "  [ok] Enabling automatic background updates at logon..." -ForegroundColor Green
    $UpdateScriptPath = Join-Path $LocalBin 'ai-update.ps1'
    
    # Security: Ensure the file exists before creating the shortcut
    if (Test-Path $UpdateScriptPath) {
        try {
            $WshShell = New-Object -ComObject WScript.Shell
            $Shortcut = $WshShell.CreateShortcut($StartupShortcut)
            $Shortcut.TargetPath = "powershell.exe"
            $Shortcut.Arguments = "-WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -File `"$UpdateScriptPath`" -Quiet"
            $Shortcut.Save()
            Write-Host "  [ok] Startup shortcut installed for user." -ForegroundColor Green
        }
        catch {
            Write-Host "  [!] Could not create startup shortcut: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    } else {
        Write-Host "  [!] Update script not found at $UpdateScriptPath. Skipping auto-update setup." -ForegroundColor Red
    }
}
else {
    Write-Host "  Auto-updates disabled. Update manually using 'ai-update'." -ForegroundColor Yellow
    if (Test-Path $StartupShortcut) {
        Remove-Item $StartupShortcut -Force
    }
}

# 9. Final summary
Write-Host ''
Write-Host '============================================================' -ForegroundColor Green
Write-Host '      Wizard-AI Environment Installed Successfully!' -ForegroundColor Green
Write-Host '============================================================' -ForegroundColor Green
Write-Host ''
Write-Host 'Available commands in your terminal:'
Write-Host '  ai-help      ' -ForegroundColor Cyan -NoNewline; Write-Host '- Central hub for all AI commands'
Write-Host '  ai-usage     ' -ForegroundColor Cyan -NoNewline; Write-Host '- View Gemini usage statistics and token budget'
Write-Host '  ai-graph     ' -ForegroundColor Cyan -NoNewline; Write-Host '- Run Graphify to map codebases to knowledge graphs'
Write-Host '  ai-compress  ' -ForegroundColor Cyan -NoNewline; Write-Host '- Compress prompt context via LLMLingua (up to 20x)'
Write-Host '  ai-rerank    ' -ForegroundColor Cyan -NoNewline; Write-Host '- Re-rank list components for RAG via FlashRank'
Write-Host '  ai-squeeze   ' -ForegroundColor Cyan -NoNewline; Write-Host '- Compress CLI outputs / files via Sqz'
Write-Host '  ai-headroom  ' -ForegroundColor Cyan -NoNewline; Write-Host '- Headroom proxy and context compression'
Write-Host '  ai-lean      ' -ForegroundColor Cyan -NoNewline; Write-Host '- Lean Context Intelligence wrapper'
Write-Host '  ai-convert   ' -ForegroundColor Cyan -NoNewline; Write-Host '- Extract clean Markdown from PDF, DOCX, images, etc.'
Write-Host '  ai-mem       ' -ForegroundColor Cyan -NoNewline; Write-Host '- Access persistent semantic memory (claude-mem)'
Write-Host '  ai-sync-skills ' -ForegroundColor Cyan -NoNewline; Write-Host '- Sync skills across all AI agents'
Write-Host ''
Write-Host 'Important: open a NEW terminal to load the updated PATH.' -ForegroundColor Yellow
Write-Host ''
Write-Host 'Your Wizard-AI directory: ' -ForegroundColor Yellow -NoNewline; Write-Host $ScriptDir -ForegroundColor Magenta
Write-Host 'Skills: ' -ForegroundColor Yellow -NoNewline; Write-Host $SkillsDst -ForegroundColor Magenta
Write-Host 'CLIs:   ' -ForegroundColor Yellow -NoNewline; Write-Host $LocalBin -ForegroundColor Magenta
Write-Host ''
Write-Host "Run 'ai-help' to see all available tools and their usage." -ForegroundColor Cyan
